In [2]:
setwd('/well/lindgren-ukbb/projects/ukbb-11867/flassen/projects/KO/ukb_phasing')
devtools::load_all("/well/lindgren/flassen/projects/omos/utils/omostools/")

i Loading omos r functions

Loading required package: data.table

Loading required package: ggplot2

Loading required package: stringr

Warning message in setup_ns_exports(path, export_all, export_imports):
"Objects listed as exports, but not present in namespace: get_expected_p, order_markers"

In [3]:
d <- fread("/well/lindgren/flassen/projects/utrs/shuffle_utrs/extdata/5utr_seqs.txt")

Warning message in fread("/well/lindgren/flassen/projects/utrs/shuffle_utrs/extdata/5utr_seqs.txt"):
"Detected 3 column names but the data has 4 columns (i.e. invalid file). Added 1 extra default column name for the first column which is guessed to be row names or an index. Use setnames() afterwards if this guess is not correct, or fix the file write command that created the file to create a valid file."

In [7]:
d <- fread("/well/lindgren/flassen/projects/utrs/shuffle_utrs/derived//14mar23//sim142.combined.txt.gz")

In [12]:
d1 <- d[d$ensgid %in% "ENSG00000001617",]


# get obs_codons
# get all codons
# for each seq
#    for ech codon
#       n = count of codons in seq
# expt_codons <- sum of n across seq
# expt_rate <- expt_codons / 10000
# oe <- obs_codons / expt_rate


count_codon()

       ensgid
1      ENSG00000001617
2      ENSG00000001617
3      ENSG00000001617
4      ENSG00000001617
5      ENSG00000001617
6      ENSG00000001617
7      ENSG00000001617
8      ENSG00000001617
9      ENSG00000001617
10     ENSG00000001617
11     ENSG00000001617
12     ENSG00000001617
13     ENSG00000001617
14     ENSG00000001617
15     ENSG00000001617
16     ENSG00000001617
17     ENSG00000001617
18     ENSG00000001617
19     ENSG00000001617
20     ENSG00000001617
21     ENSG00000001617
22     ENSG00000001617
23     ENSG00000001617
24     ENSG00000001617
25     ENSG00000001617
26     ENSG00000001617
27     ENSG00000001617
28     ENSG00000001617
29     ENSG00000001617
30     ENSG00000001617
<U+22EE> <U+22EE>
971    ENSG00000001617
972    ENSG00000001617
973    ENSG00000001617
974    ENSG00000001617
975    ENSG00000001617
976    ENSG00000001617
977    ENSG00000001617
978    ENSG00000001617
979    ENSG00000001617
980    ENSG00000001617
981    ENSG00000001617
982    ENSG00000001617
983    ENSG00000001617
984    ENSG00000001617
985    ENSG00000001617
986    ENSG00000001617
987    ENSG00000001617
988    ENSG00000001617
989    ENSG00000001617
990    ENSG00000001617
991    ENSG00000001617
992    ENSG00000001617
993    ENSG00000001617
994    ENSG00000001617
995    ENSG00000001617
996    ENSG00000001617
997    ENSG00000001617
998    ENSG00000001617
999    ENSG00000001617
1000   ENSG00000001617
       seqsim
1      GGCCTTGCCCGGCCCCGGCCCCGATGTTAGGGGGGATGGCCCGCGCGGAGCAGTCCTCCCAAGCTCGCGCCGCTTTGCGCGGCCCCCGCCGGCTGCTGGCGGTAGCCTTCTCTCCCGCCCGGGGCCTACGCCGCAGGCGGCCGCAGGGCTGCCCGGCCGGCGAGGCAGAACGCCTGCCTGGCCTGCGAGCCCCCGACCCGTCGGCCGCAGGGGGGGGCCGCCGCCTGACGCGCCAGAGCCCCGTCCCGCCGGCTAGAGGCCGGAGAGGGGACCGCAAGGATGAGCGAAA
2      GCCGGAGATGCCCGCTGGGCCTAGCGCAGAAACGGTCCGCCGCGGGCAAAGGGCCCGCAGCGATGGGGGCCAGCGAGCGGCGCCTGGGCCGCCCGGGCTCCGAGGGGCTTCCCTGCGCGCGGGGCCAGAGCCGCCCTCGTCCGGGGCGGCCAGCCCCCCCGGCCGGGGAGAGGTGACGCCCTTTCGCCTGTGCTAGCGAGCTCCCCCTTCCCCGCGGAGCCGGCCCGTGGACATGGCGACACGCGCTTGGCCCTGGGCGGCGCCCGCGAAGCTAGCTAGCCCCCCCCGA
3      GCCCCGCCTAGCCCGCAGGACCACCGGTCCCTCGAGCGCCCCCACCACCGGCCGGCCCGGCAGAGCCGGCCGGGCTGCCCCCTCCCCGCCGCGCGCCTTCAGCTCGTGCTAAGTGCGCGGGCTAGCCCCCGGCGAGGGCTTGAGCTTCCCGCCCGGGCGGGGCCGGGAGCCTGGGGTCATCGCCGCCCCGGCCGCCCGCCGTTGAAAGGGCTGGCTGAGCGCGCCGGGCTGGCGAGCCGGGGGGACAGCGCGGAGAATATTGCCCGAGGAGGCTGAAGGCGCCTGGCGA
4      GCGAGAAGTAGCCAGCTTGCTGGAAGCCCGCCCGGGGGAGCGGGCCGGGGGGGCTTTCCGCCAGCCGTGGCCGTCACGCCGCAGGCCTCCCGCTCCGAAGCCGGCTGGAGGGGCGGCGCCGCGCCCCCCCCTCCTGGATGCCCGAGCCCTACGGCCTGGCGGAGATTGCGGCCGCCCCGAGGGAGCGCCTCCCAGCCCACTCCTGCTTCCGCCGCGGCCCCGGGGGAGCTGCGGGCTAGGCGGCGCGCCCGTGGCGGTGCAGCCGCCCGCGCGAAGGATACCGACCCAA
5      GGAGTGCGGGAGCCGCCTGGGGGAGCAACCCCCGGCGTCGGCCTGAGCCCGCGCAGAGCGTCCCTGGAATGAGGAAGCTCTTAGCGCCGGCTCCCCGCCCTGCCCCGCGAAGGGGCGGCCGACGGGGAGGGGCAGGGCGAGGATCTGCCCCCCGCCTAGGGCGGCCGCCGCTGACCGGCGCCCGGCCTAGCTTAGGCAGGCCGCCCGCGGATTTCCAGCGGGCGCCACGCGTCGGGCCCCGCCCAAGCGCCGGCGCCCCCCTGACTCCGTGCCCGCTTGCCGGGCTGCA
6      GATTCTGGGCCCTGCCGGCCGGGGCAGCGGGGGTTGCGCCGGCGGCCCTTAGCTGGACGCCCGCTCCCCCGGGCCGGCCATGCCCCGCGCGGGGCTGCCCGGAAGCCCCGCGAGCCCAGGGCCGGCCCGCCTGCTGAGACGGCGCTGCCGCCCTCGCGCGTGGCGGAGCCCCCGCCGAGCGGGAGCGCAGGTGGATCCTCGGGAAACGGGCCGGAGCAGACTCCCGCCCGCGCCGGGCCCCCCAGCGAGCCTTTAGAAGTCCAGTCGGAGCCTGGCGCAAGGCTACCTA
7      GAGCGGCAGGCCCCCGATTCCGCCCGATGCCGGCGAGGCCTGGCGCAAGCTTGGATACCTGGCAACCCGGCGGGCGGGTTAAGGGCCGGGAGCCCGCCCGTGCCCCAGCCCTCTAAGCCGCCCTCGCCGGCCCCCGGAGCGGCGCCTCGCCCGCTGGCTGGACGCGTGCTTGGAGGGCCCGGCGCTTCCCCCCCGCCGCTCAGGAGAGGCAGGCGGGGCTCGGTGCCGGCCCCCAGAGCCTGCCCGCGAACGCGGGCAGGGGAGCGACTGGGCCGAGTCGCCCGCGCTA
8      GCCCGCCGCCAAAATGGCGCCGGGCTCCGCGGCAAGCGGCCGCATTCGGCGGCCGGCTTGCCGCCGCGGGCGTGGGAGGACTGCTGGGCCCCCTCAGCCTGGCCGCCCCCCCCGGGGAGCCCTGGGAGCTCCCCCTACCCGATGCGGGCCGGCCTTAGCGGACGCCCGCAGGCGTGCTGGAGAGCGCGTCTGGCGCTGAGCCCCGGCCGGGAGAAGCGCGCCTTCCGGAGCCCCCGGGCGTAGGACTAGCGCAGGACCCGGGCGGTCCGCAGAGCCCCCTTCAGCCGGA
9      GGGCCCCCAGGCCCGATCAGGCGCGCCTCCATGCCCTTCCTGCCCGGCCGCTGGCTCGCCCGAGCCTAGGCGGCCCCGCCGGGCGCGGTGAGGCCCTAGTTCCGGCGCCCGGCGCAAGGACAAGGACAGCCCGCTGGGGCCCCCTCGCGCGGCAGGCCTGGTCTTAGCTAGGCGGCCGGGCGTTGGCGGCCGCTGAAGGCCGAGCTCCGCTTGGGGCCAGAAGGCGAGCGCGGACCCCCGCCCCGGGGCCGAGGACGCGCCCCGACTGCCGCCCGTGGAATGAGGCCGA
10     GGCCAAGCGTCAGCTGCCAGATACGAAGGGCTTGCCTCCCTACTGAACCCCGCGCCGCCTAGCCCCCCGACGGCGGGGCGGGCCGCCCGAGCGGCTAGCCCGGGCTGGCCCGGAATCCGCCCCCGGGCGAATCGGCGCCGGGGCCCGCCCCGCGGCGGGGCCAGGCGGAGGGTGGCCCGCCTGAGGGGTGCCCTGGGAGAGTTCGCGGGAGCCTGCGCCCTTGGCCCGTCGAGAGCGCCAGGGGCTTTCGCAGCTGCGCCTCGAGCCCTGCGCCCGCGCCGCCCAGACA
11     GCCCCGCCGCCTAGGGCGCCCTTCAGCGCCTAAGGGGCCTAGCGCTGCAGAAGGAAGGCAGCCGGTGACCCGCGCCTCCCGCCGGCTGATTCCGGGCGTGGAGCGCCGCCGGGAGCGCGGGCAGCTCCCCGCTCGCATTGGGCCGCTCCGGAGCCGCCAGGGCGCGCTCGCGGAGGGCGGAGCTGGGAATGCGGCTGTAGCCCCGGGGCCGCCAGCCCTGGCCCCCCGACCCGACCCCTGGCCGCCCGGCCGGAAGACCGAGGTTGGGCGGGCTTGTCCGACCGCCCCA
12     GGGCGACACGGGGGATCCGAGCCCCGGCGAATAGCTGGCAGGCGCAGCCCCGCCCCGCGCCGCCCGGACGAGCGCGGAAGAGCTCCAGGCGGGCCCCCATACGCGGCTCCTTGCCCCCCGGGCCGGCCGCCTGCCCGCCGCCGCGGCCGCCTGGTGCCCGCCCGCGGCGGCCGTCCGAGCGGCCAGAGGGGCCCCCGCTTGCTGCCGGGCTGCTGTTCTAGGCGTAGGAGGCCTCGAAGGCTGTCCGGCCAGAACCCTCCCTTGGAGCCAAGCTTGGCGGGGAGCGGGA
13     GCGCACCCTCCAGGCCGGGGCGAGGCGCTGCCTTTAGCCGCGCGTGCCCCACTCCCCCGCGGGGGAAGACGCAAGCGCCTCGGCCCCGCTGGGGGCTTGCCTGCTCGCGGCGTGGGCCGACCGGAGGCCCGTCCCCCGCCGGCGCCAGGGAGCCTAAGATGCCCCGGGCTGCCCGAGGAATCTAGAACCTCCCTTGGCCAGCCCGGCCCCGCGGAGCCGAGCGCCGGGGGCCGTAGGCCCCCGCCGCGCGTGGCGGCCAGAGGAGGGAGCGCGCTGATGGCCTTCGGCA
14     GAGGCCGCGGGCCAGCGCGCCCGCTGACGCTAGGGGCCTCTGCCGGGCAGACCGGCCCGCCGTGCTTGATGAGCCCCTTCGCCCGGAGCCGGCGGGAAGTAAGAAGGCCCCCCGCTGCCCAGGCCGGCCGGAGCCGGAAGCGGCCGCGCCCTCCCCTCGCGCTCCGCCTGTAGCCCCGGCGGGCGTGGGGCGATTGGCGAGAGGGGGGTTAGCTGCAAGCCCGGCCCGCGGCCACCCTTCCGACCGATGGCCCCCGCCCGGCACTGCCGCTCAGCTCGCAGGCGGGGGA
15     GTAGCTTTAGAGCCGCCGGCGAGAGCCTGGGTCGGCCGGGCCCCCGCCGCTGGCTCGCACTGCCGGAAGCCGCCGGACTGCGCTCCGGCGGGAGCGCATCCAGAGCGCCCGAACCAGGGGCCGCTGCCCGGGGAGAAGGGAGAATTAGCGGGCTGCGAGGGCCGCGCGTCCGCCAACAGCCCCCTGGCCTGGAGGGCTTCCCGCCGCCAGCGGCCCGGCGGCGGGGATCGCCCCCTCCCCGCCCCCCGCGGGCCGGCCCCCTTGGCCCGACGTGTGGGCTGCAGCGCTA
16     GGGCGGCATCCGAGAGGCCCGCGCCCCCTCCTAAAGCCCCCCCTGCCTCCCTGGCGCCGGGGGGTGGAGCCCGCCAGCCAGTTGCTAGCCGGCGCGGCTCCTGAGCCGCTGGGGCCCACCTCGCCGAGCGAGGCCAGGGCTGCGGCGCGGCTGAGACCGCAGCCCCGCCTTGCCGGAAGGCTTAAGAGGCGGCGCGGGGGCGTGATTCGGCCCGCGGCGGAACAGTTGCGGGCGGCGATCCGAGGCCCCGCCCCCCGCTGGCGGCGACCGGGTAGCCCCCCGCACTCGA
17     GAGAACGGGCGTCGAGCCTGGCCCAAGCCGCCCGGCGCTCCAGACCGGTGGGACGGGGGCGCCGCCGAGGGCCCCGGGCGCGGAGGGCCTAGGGCAATCTGACGTTCCGCTGGCCCCGCAGCGCGGCTTAGGCGCCCAGGTGCCCAAGCGCCGAGCCGCCGGAGCGATGCCCTGGCCAGGCCGAGCCCCCCGCCCTGCTGGGGGGAGCTCTGGCCGGAGCCGAACGCTTCGGCGGGCCCCGAGTCGGCCCCCGCCTATGGCTTGCCTTCGCCGGCAGCGCGCCCCCCTA
18     GCAACGCGATCCCCCCGGATCCTGGGCGCCCTGCGCTTAGCGTTCGTGGACCGAGGCCACTTCCGGAGCGCGGTGCTGAGACCCGCCCACCCCTGGCGGCCCCCGCCTTAGCGCCGCAGCCCCTAGGCGGCGCTGCAGGAGCGCGCGCTCCCTCGCTGGGGCAAAGCGGAGATAGCTCGCGGCCCGCCGAGAGCCTCCCGTTGGCGGGGCCTGTGGGGGCCGGCCCCCCGGGCGAGCGGGGCCCGAGGAGAGGGCCCGGCGCCGCCAAGGCCCGCCCGCTGGGGGCCAA
19     GAGCGGGGGCTCCGACCCCGGCCCCAAAGCGCGCCGCCTCGCCAGCCCGGCCTGAGGAGGCCCCCGAGGGGAGCGCCACCGGCGGGGTGCTGCCTTCCTAAACGCGGGCTGCCCCCGAGCGAGCTGCGCCCTATTGAGATGCCGCCGGCAGAGGCCACCCAGCAGCCCGTCGCGGGGCGGCGCTTCCGCGCCCCGCCCTTGCGGGGGAGGCGGGGAGCGCCCGAGCTGGGCGGCCCCCGTGCCCCTCCGCGGGGGGTTCCAGGACTGCGCTCGCGCCCTGCGAATAGTA
20     GGTCGCCGAGGAGCGAGGGCTAAGGCGAGGCCGCGCGATGCCCGGCAGCGGCCTGCCTTGGGCGATCCTTGGGCGGCGAGCCCCCCCCGACGGCTCGGGGCGCGCAAGAAGCCGGGCCCCGAGCCCCCGCAAGCTGAGGGCCCCCACCCTCTCTGCCAGCTTGGTCGCTGGGGGCCCCGCACGGCGCTGCGCCCCCCTACGAGCCTCCGTGGGCGATGGGCCGGCCAACTTTCGCCAGCGCCCGCGTGAGGCCGGGCCGTAGGCGGGCCGGAGCCCCTAGGCGCCCCGA
21     GAGCGGGGCGGGGCCCTCGCGGCCAAGCGCCCCTGGGACCAGCGCCCAGGGAGGGGGCCGTAGGCGGCGCCGCTTCAGGCCGCCTCCCTGAAGGGCGGTCCAGCCGCGGGCGCCTGCGCCCCGAAGCACGGGGCCCCCGAACCCTGGCTGGATCCCCGGCCTGCGAGGCGCGCCTCGTGCCGGCCGCTCGAGCCGGGATTTACAGCCCGCCCGCGGCCCTGCTAGAGGCGCGGGCCCACCCGGTGCCGAGCCCTTTGGGCCCCGATGAGAGCGAGTGCGCGCCTCCTAA
22     GTTGGGCGTGCAAGGAAGCGCCGGGAGCCGTCTGGCGCGCTGGCCCCCCTTCGGCCTGGCCCTTGGAGCGGGATTAACGGCGCTGCCCATCCGCCCCCGGGCCCCCCTGCAGCACCGAGGCCCTTGGCTACTCGCTCGGGGTCGCTCAGAGCCGCCCCGAGCGCGGCCAGCGGTGCCGCGGAGCCCCGGGCCGCGGGCCGCGGAACCCGGGGCGGGCCGGGCGCCGAAGCCCCCTAGCCGCCCTCGCCCTGGGCCAGAGAGGCGATGCCCGCGAGACGCCTAGGGAGCA
23     GGCCCCGTGAGAGAGCCCCGAGGCGCCCCCGGTATGGCCCGCCGCGGCTGGGCGGCGGGCGCCGCCATCCCCGCTTTCTGGCCCCCGCGGCTGAGCGAGGGCGCCCCTCGCGGGCGGGGGGCCGCCCCCCGGACTGACGCTGGTGGCCGCGCCGGCGTCCCAGGCCAGCTTGAAAGGCGCGCCCTCTTTAAGCACCGAGCTAGGCGCGCCAGGCGCTATCAGCCACCTCCGAGGCCCGCGGCCTCGGAGTGGGGGGAAAGCTGCCGGCCCTGGCCCGAGCACCCGGAGA
24     GGGGGGTACTGCCGCCGCTGCCCGCGCCGGTGTTGGAAGCCCCCAGGGCCTTGCTCCGCCAAGCCGCCGCCGCGGCGCCTGCCCGCTCTCCCGCGGGAGGCCAGATGAGATTCAGCTGGCGCCTCCCCCTTCGGCCTGGAGCGGACCGGGCGCCCCCAGGGCCGGAGCCTGCGCGGAGTGCCCGGCGCGGCTCTAGCGCCCCCCGCCGGGGTTAAGAGGACGGGGCGCGGCTGCCCCGCGGCCTAGGGCACAGGAAGGAGATCCGCGGCCCGAACGAGGCGCCCCGCCA
25     GCCGCCCGAGCCAGCCCCCCCAGGGGGCGCGCGGGAAGCTGGAGGCGGAGGGATCGGCGGTGAGCATTCGGCCGCCTAAGGGCCTTGGAGCCTAAATCAGCCCCGCTTACGACCCTTGCCGCCCCGGGAGCGGCTGGCGCGGAGCGCAGCGGCTGCCACCGAGTGCTCCGGCCCCTACGGTCCCGCCTGCGCCCGAGTTCGCCCCCCTGGGCCGCTGCGGACGCCTCCGGCCGGCCCCGCGCGGCCCCGAAGAGCCAGGCGGCCCCGCGCAGGGTGGCTCGGCTGGGGA
26     GAGGCCCCGCTCCCCGCCCTGCCGCTCGGCCGCAGCGAGCCTGCGGTCGAGGAATAAGAGCCGCCCTTTTCCCCCCGGGCTAGCCATGGGCCGCCCGGTGCCAGCGAGCCTGGCGCCCCGGCGGGGCCCCGCCAAGGCGCGGCCCCCGTTAGCGCGGCCGCCGCGCTCCGCGCCCCCTGCTTCCTGGGCCGCGGGGTGGTACGCCTGCGGGGGGGCAGCTGCCTCTGCACCCGGGACGCAAGAGGGCGGAGCGGATGCCCGACACGAGCCTCCGGAGAAGGGCGGGAGA
27     GCCCAAAGCGTTAGGGGCCCTCCGCCGCTGCCGCCCGGCTGGGCCCCCTGGGCATTGCGCAGGAGGGCTTGGCTCCGACGCGCCGCTACGCAGGCCCCCCCGACCGTGCGGCGCGACCTACGCGTGGGGCCAGGCGGGCCTGAGCGCGCCCGCGGGCCAGGCTCCGAGTCTATTCCGCGAGGGAAGATTGGAGCCCCAAGGGCCGAGGCGGGCGCGGGAGGGGCCGAAGCCGCGAGCGCCCCGCTGAGGCGTCCCCCCCTGCCGCAGCCTCCCGGCTGCCTCCCCGGGA
28     GCCGCGCCCCCCGACTGAGGCCGAGAGCCGGAGCCCTAGTTAGCGGAACGCCAGGTGGCGCCGGGGGGGCGCAAGTGCGACCCCCCTCGGGCGCCCCAGGCTGAAGACTCTCAAGCCCCCGGCGGCCTGAGCGGCGGCTGGGCGCCCGGCGGCCCGGGGGGCGGCGCCTTTGCCCGGGCCTGGGCTGCAGTCGCTGGGCGCGCGCCATGCCACGCCGAGCCTCCCCCCCCCGAGCGCGGATGCGCGCCCTATCCGGAGGCCAGTCTTTAAGCGCCCCGAGGGCCTCGGA
29     GGAAGGCCGAGGCGGAGCGAAATGCTGCCCCCCCCCGCGCGCTAGCAGACGGGATGGCCGGTGTGCCTGTTAGCCCCAGCGGGAGAGGCGGCCCGCCCGGGGCGGGGCCGCCTGCCCTGCCGGGCGAGGGAGCTCCCCCTCAGAGCGCGCGGCCCGGCCGGCCCCGGCTCCGGCGGCGCCTTTAGCCGGCCTCGACCCCGCTGCCCCCCCAAGGAGGCGCGTCGCGCTGGCGGAGCGGCACGGGGCATCCTGCTGGGTTACCTTCAACGGCCAGAGCGCCCCTCCGCGA
30     GCCTGCCTGGCCGCGCGCTAGCCGGCCGGCCGCCCTCTTCCGCGGAAGCAAGCGGGAGCGAACCCAGCCTTCCTCGGCCGATCCCCTGCCGCCCCGCCGGAGGCGGCCTCGCGGTGCGCGGGCCAGGCCCCCAGGGGGGGCTTCCCCCCGGCCTTTATAGCAGGATACCCCTGGCCCTGCGACCCGGGAGCGGGTGCGCGGCGGCCGGCTGCGGGACAAGCGAGCCTGCCGGAGGGCCCAAGTGAGGCCCCCGCAGCGCCGCGGTGCTGCCGAGAGGACGTCGGCCGGA
<U+22EE> <U+22EE>
971    GAGAGACCGCGGCTCCCCAGCGCGGGGAAGCTGGAGCCCGCCCGGGCCAGCCCCAGCGGCTGGTGGAGCCGCGCAAACGCGCGCCGGCCGCCCTGCCGCCGCGCCCCCCTGGCCCGCCCCCCGACGGCAGCCGGCTGGGCGCGCTGGGATTATCCGGCGGAGGCGCCGGGGTAGAGAGTGATTGGGGGGTCCGCTCGCGCCCCCTTGGGGCCCGAACCGGGCGCCGGCTGCTCTCCTTTAGCGGCTGAGCCGCAGGGCCCGTCAAGAGGGCCCCTCCCTACGCGAGCCA
972    GCGGGTCGCAATGCGCCTCCGCCCGCGGGGATGCTCGGTCCAGCCCGGCCCGATTGCACCGAGCGGGCGGGCCGAGCTGCCGCGAAGAGGAAGCGGCCTAAGAGCTGCGCGCGCTAGAGCCTGCCCCCAGGGAGGGCGCTACGGTCCCCCGGCCTGCGGGCCCCTGCCCCCGCCCAGGACTCAGGGGACGCCGAGCTGCGCCTTTCCCGGGCCCCAGGCCAGGGCGCGGCGGACGTTCGTTGGAAGGCCTGCCGAGGGCCCTGCGCCGGCCCCCGGGGCGCCCCGCCTA
973    GAGGCCCCAGCGCGGGCGGGCCTCAGCCCTGCGGGTGCCTCCCGCGCGCGCGGCTTGGCGGCGAGGCCGAGAACCCCCCTGGCGGCGCTCGGGAGCTGCCCTCAGAGGGCCGAAGAAAGGGCGCTCCAGGGCGATGCCCCGCCTGGCCTCCCCCCTACGGAGGTGCCTTTGACGCCCGCCCTCGCCGCCGCGGGCGGAGCCGCCCAGCGCCGCGCCGTTAGGAGCGCCCCCCCCCGGGATAACAGCTGTCGGGGGTTGCCTGAGCCGGCATACGCCGGGGGCAGGCCGA
974    GCCTGCGTTGCGAGGACCCGCCGAGTGCGAGCGGCCCTGCCGCCCCGGGCGCGGCCCAGCCGCAGGGCGCCGGGACTGGGCGTGGGGAATTCTGCCCTCCCGCCGAGCGGCGCCCCCCCCTGCCCCGGGCGAAGAAGCCGCCGCAACGAAGGGCCAGGGCCTGGCGCCGAGGGACGCTAGCCCTTCCGCCCCCGCGGGTCGCGAGGGCAGCTCGGCCGGGGCGACCGCTAGGGGGCTGCGGGCATATGTCCCCCTCGCCCTTCCGAGGCCCAGGCCTTGCTAGAGCGCA
975    GGGAGGGGCCTTGCCCCCCGAGCAGTAGCCCCCGAATGTGAGGGCTAATGCGCCCCGGCAAGAGGCTGCCTCGGGCGGGAGCGGGCCGCCCCGAGGCCCCGAAGGGGCTCTGTCTCCGCCGCTCGCGGGTCCGAGGCGGGGCCCTTCGCCCCCGAGACGCCCCGCCGGAGCCATTCCGCCCCTGGCTACCGCGCCGGAGACTTGCAAGGGCGCGGGGCCGGAGCAGCCCTGCGCGCACCGCGCCAGCCCTGCGGCGCTTGGGGCCGCGGTAGCGCTGCGCCCCCGGACA
976    GCGGGAGAGAACGGCCGGCCGGGGGCCGCGGCCCCGCCCCAGCCTCTTCCGTTTGCCCTGGCATGAAGCCTAGGAGCCGGCCCTCAGCTCCCCCTGGGGTGCCCTAGGAATGCGGCCCCAGCCCCGGCTTGGGAGCAGCGAAGGCCTGGGGGCTGGCGCGCCCCAGTGCCGAGCGACCCCACGCGCGATGCTCGCCTGTTCCGGCAGGGGTAGGCGCTCCCGCGACGGCGCGGGCCGAAGAGCTCCGGGCCCGCTAGCGGCCGCCGCCGCCCGGCGGCCGGACGCCCGA
977    GAGGGTGTTAGCTGCGGGGCTGCTAGATCGTGAGCCGAGCACCGTAAGGCCCTGCTCCCTTCGCCGACCTCCCGCCGCCTTCGCGCCCAGGGAGCCCTGGCGCGCCGGCCAGCGAGCGGCAAGGCCGTGCTCGCGCCCGCCCGCCGGGAGCGGGGCGGCTTGCCCCCCCCCCGCCGGAGCCCAGATACCGCGCGGGCCGCTGCCTCGAGCCCGGGCGCCCCTTGGGGCCGGGGGGGAGCTCACCCGCCCCAGCACCGCGGGCGAAAGGCCTGGCCGGAATGGGGAGCGA
978    GGGCCCCGCGAGGCTCCCGCCGCCGAGGGCGCCGGGGTGCTGAACTTGGCCCCTGCCGACCGGCCCCGGGCCGCCAGGTCCCGAACTGGGGCTCCCCGCCAGCCGCCCCGCGAGCCATAAGGCTGAGCGGGCAGAGCGAAGGCCCGCAGCATGCCTAGGCGGGGCCTCCGCGGCCCCCGCAAGAGCGGCGGGTCTGCCGAGACCCGCGCGAGACCCGGCCTATTCCCTGGCGCGGAGCCGCCTTGGGGCGCCCAGGGCGTGCGCCTGGGCGGGCCTTCTCGCCGAGTTA
979    GGAGCCCGACCGGGCCGGCGCGCGCCGCCGGCGAGATGGAGGCAGCCTCCCCGTGCGAGCCCGCGGCCGACCCTGTAGCTTTGGGAAGGGGGTCCCGCTTCCGAGAGCCTGGCAGCTGGAAGCCAGGCCGCAGCGCTATGCCCCCCCCCAACCCGCCCTCGCTCGGGGCCCCTTAGAAACTCAGCCGGGGCCCGCCTGGCTTGCTGGGGAGCCGGCGGTCGCGAGACGCCGCGGAGCTGCGGGCGCCGGCGCGTATGCCGGCGCAGCCCCGGGGGCTCCCCCCGGGCCA
980    GCTATATCTGAGCCCCGCCAGCTCCCGCCGGACCGGCGACCGGCCGCCGGGGGCGGCGAGGCGTGGGGGCGGGGGCAGAAGGGCTCGCCCCGGAGGGCCGGGGTCCTGGCGAGCTAGCGAGTCGGGCCCCGAAGGCCCACGGCAGGCGCGGCTCTTGGCGTGACAAGCCGCCCCCCTGAATTAGGCAGCCCCGCCCTGCCGCTCCCCGGGCCGCGCCTCGAGGCCCCTTTGCCTGCGCCGGCAGCGCCCCGCTTGCGAGCGCCGAGTGGGAACCAGCCCCTGCGCCCGA
981    GCGAGAGAGCGCGCGGCCTTCGAGCTGGCTCCCGAACGGGCCCCATAGCCCCAGAACGGGCCCGGCCCCCTGGCTACCGGCGGGCGCGAGCCCGCGCGCAGATGAGCCCGGCTTTGGGCGTGCGTGCGCCTCCTCGGGGGTCTGAGGAGCATAAGCCGGTCCCCAAGCCCCCGCCCGCGGTGACTGGGAGCCCGGGCGCGCTTGCCCGCAGGGGGCCCTTCTGAGGCGCAAGGGGCCGCGCCCACCGGCCGCCCGGCCTCGCGCGGCGCCCCTGGAGGGAGGCCCCCTA
982    GCCCATCCCCCCCGCTTGCGCAACCGGCGCCTTCGAAGCCCGGCGGCGGCCGGGGCCAGCTGGAGCTCGGAGGCCGGGGCTGCCGGTGCGTTCTGCGTACCGGCCGCCCCCCCCCAGGCCCCCCTGCCGAGCCGATAGGCGGCGCGGAGCCGAGGTTGGCTGGCCGAATCCCCCGCGCTCCCGCGCAGAGCGGCGCGCGACGCGGCTGGGCCGAGGGCCTTGGGGAGAGCTGTGGGCAGCCCCACTCGCCCCGCGGACCCGCTAAGGGAGGCTCCTAGCGAAGGGGCCA
983    GGGCGGCGCGCAGCGGGAGAGGGCGGTAATGGGGGGCCTTCATTAGGGCGAAGCGCTAGCCCGCCCCTTGCCTCTCGGTGTGGCCGCGAGGCGAGCGGCCGGCCGCGGCCTGCCAGGACTGGCGGGCCCTCCGGATGCTTCCGCGCCGGCCGTCCTGCCAAAGGCCCCCCGGCCGAAGCGGCCGGAGAGCGAGCGCCCCGGGAGCCCGCACCTGAGGCGGCCCCCCCACTGACCCCTGCGCGGCCGGTCTGCAGAGCGGCCCGCCCCGCCCCACCTTAGGGCCTCGCGA
984    GCGCGCGAACAGGCTCGGGCCCTCGCGGCTGCTAGAGGGGCGCGGAGGCTCACCGGCACGAGGGCGCCGCCCCCCGAATTGGCCCCCCGGGGGCGCCCGGCCGCGCGCCTCGCTGCAGAGATCGGGGTGCCTCAGAAGCCAGCAGCCCGTCCCCCGGCCCGCCTGCGAGTGCGGGGCGAGGGCTAGGGGGCCCGGCTTTGGCCCCGGGCCGAGCAAAGCTGCGATGAGCCCCCGGTGGAGCCCCCCCGCCCCTTGCCCCGACTCTACCGCCGGTGCGCGCGCTTAGGGA
985    GCGCCGTAGGGAACCGGTGGAGGAGCGTGCCGATTAGACCAGGCTCGAGCGCAGGCGGCCCAGGGGGCGTGGCACGCCTTGGCCCCCGGCTGCCGGCTGCTGCGCCCCCCCCGCCGCGCGCCGGCCTGGTCCGAGGCGGGCTCTTGGCGCTAGCAGCGGAGCCTTCCCCCGGGCCGGGATGGCCCCGCAACTCTAGCCCTGGCCTTCGGCGGCCCCCCCCCCCGAGCGCGGGCTGCGCGGCGGGCTCCCGCGAGCCCGAGGGAGCCAGCCCAAAATCGGAGCGACCGGA
986    GACGCCCGCCAGCGGGCCCGGCGAGCAAGCCCTTCCAGGCGGCGAGGCTAAGAGGCGCGGAGGTCCTGAGCCCGCTTAGGGAAGGGGAAAGCCCCCCTGCCCGCGCCCCCCCGTGGGCCAGAGAGAGCGGGCGGGCCGCTGGATGCGGGCTCGCCCCCCGGCGCGCCAGCCTGACAGGGGGGCGTACGCCGCGCGCCCTTTGCCTTCATGCGGGCCGGATCCCCGCGGACTACCTGCCTCCGCCGCCGCTGGGCTCGCCGCTCCGGCCGGGCGAGTGGTGGCCCGCCCA
987    GCAGCTTGAAAGCCCTCGGAAGCCAGCCGGCTGCGGACGCGAGCGGGTGGGCGGCCGCGGGCTCCCCCGCCCCCCCGCTGCAGGGGCTTATAGGCCCGCGAGTGCTGCCCTGCCGAGTGGGCCCGCCGCCGGGCCCGGAGGCCAGACTCACCGCGCCGGGAGCCCCCAGCCTGCGCGCCCCGCCCGACCCCTCGGCAGCCTTCCTCCCGCGGAGGTAGCCATTCCGGGCGGGCGCTCGCTACGAGGCTGGGGCCGGGAAGCCGCGAAGGGGTGGCCCGATTGCCGGCGA
988    GCTGAGAAGGGGGGCGGTCCTGGCAGCCCGCGCCGGGCCTAGCTCCCGCGCGCGCTGGGGGGGCGGCCGCGGGCCGGAAGAAGATGAGGCCCGGAGCTTGCCCGCGCGCGGGGCGCCTCGCCGCCGGCAGCAGGGGTGCGCCCACTTGCCAGCTGCCCGATACCTAGGCGAGGCCCCCGCCGGGTGCGAGCGTGCCCCCAGAGGACCCTCCCAAGGCCGCTCCCCATTCCCTCGGCGCCCCCGCCGCCCTAGCGACGGGGAAGCCGCTTTCCGACCCCGCTGGGTGCGA
989    GCGAGCCGCGCCGCATCGCCCCCGGGGCGCCGGTTGCGCCTGCGGCCCATGGGCCGGCGACGGTCGCCCGGGCTGAACTAGGGAGCCCCACGGCTTGCCTAGCAGGCTAGGCGGAGAAAGCGGCCCCCGGCGCAGGGAGGAGGCTCCGCCCCCCCCCTGCCGCCCGCCTCCCGGGAGGAACAGAGCTTGCCTGACCGCTGTTCGAGCGGGCGGGCGCGCCGCTATCCCCCCGGCGGGCCCCCCGGGGAGGAAGCAGGCGGTCGCCTGCCCCGCTGCGCGGTCTTGAGCA
990    GCCCGGCCCCGCGCTAGGCCGGCTACTTGCCCGCCCGCGCGCGGGGCGGGGGATCGCCTTGCAGGACGGGGGAGGTGCCGGGGCCACAGAGCCGCGCCCGTGCCGCGCAAAGGCCCCCTCGCGCCCGAGAGGCCGGGCTGGCCGGACTCCCCGTAGTGGCCCCCGCCGGCGCCCGCGCCGCAGCGGCTCCCTGCTTTGGCGGGGAGAACCAGCGCAGAGAGGCGCCCTCTGCTTCGCCGGGAGCCGCCTCTCCCCGCCCCTGCCCCATGGGAGGAAGTAATGGCGAGGA
991    GCGGGGTAGGCAGTCCCTCTTGTCCTTCGCGAGAGGCGAAGCCCAGTGGCCGACGCCCTCGGACCCTGCCCCGCCCGGGGAAGCGCTTGCCCTCCGCAGGCCCGGGCGAGCTAGACCTGATTTGCTGCGCAGCCAGGGGGGCCCCCCCAAGGCCGCGCGGCCAGGGCCGGGTACCCGCCGGCCCCCCGGCGGCCAATGCCCTCCCTGCGCCGGCGGGGCGGCCCGCGGCGCGCGGAGGGCGAGCGCCTGCCCGGAGCCGATACCGGCGCTGAGCGAGCTCTGGGCCGAA
992    GCCGGAAGGCCCGGGCTGCCGCAGCCGGCCCAGAGCTGAGCAGATGGCGGGCTGAGCCGGTCCCCCCCGGGCCCGGCCGCGATGTCTGGAGGACCCTTTTTGCCACAGGGCGAGCGGCCGCCCGCGCTCCCCCGGTAGCGGCTCGGGCGGCTGCGGCCCACCGGCCGGCTGGGCGCGGAATCCGCCCGCTAGGCGCTCCCGGACCCCCTGGTTCGCCGCCTAGAGCCCTCCGGAAGGGGCGGCGACCCCAAGGAAGCGCCTGCGCCCTGCCCGGCAGAGCGGCGGCGTA
993    GAAGGAAGCGAGAGCGGTCGCTTCGGGGCTGCGCTCGGCCGGGGGTTGGAGCGCGATGCCCGGGGCCGCGCTTAGCGGAGCCGCCCGGCCCGCCCCTTGCCTAGATGCCCTCGGGCAGGCCGCCGGGCTTGCGCGCGCGTCGTGGCCATGAAAGCGACCGCCCCCACAAGCCGCCCGCGAGGCAGGCCGCCGCCCCTACTGGCTACCCACCTGGGCCTGCTGAGGTCAGCAGAGGAGCGCGGGGGGCCGCCCGGGCCGCGGGCTCCCCCCCCCCCTCCGGCCCCGGAGA
994    GGCAGACCGACCCGAAAATCGGCCGCTGCGCCGGCAGAGCCCCCAGCGCCCCCGACGCGCCCCTGGGGGGGGCGCATGCGCCTTCCCCCCCGTTAAGGCCCGGGGCCTGGGCGCTCCCGGAGCGAGGGCGCCGCCCTGGGGAGTAGCGCGAGGCGCCCATGAGGGGCTCGCCCCGCCGGGCGCCCTGCTAGCGTCCCAGCCGCGAGCCTGGCGTGCGCTTCGTCCTCCCTGGAGCTGGGCGGCGCCGCTTTAGGGCGAGGCGCCCTGCCAGGGGGAAGCGACCCCGACA
995    GCTGCCCTCCGCGGCCAAAGGGGCCACTGCCTTCCTTAGGGGGGCGAGCGCGCGGGCCGGCCCCGCAGCGGCCCTGGACCGCGCCTCGACCGCCGGCTTCCCCAGTCGCGGGGGGTGCCGGGCGCCAGCCCTGCCAGGAGCTCTGGCCGTAGCCATTGCTGCCGAGACCCGCGGAGCCGGCGGCCTTAGGAATGCCCGCGCCGGAGCGAGATGCGCGCGCCGGGGGTGACCCCCCGAGGAGGCTCCCCGGGAGTCCGCCGCGCCTGCCCCCCAGCGCCTAAGGGCGGAA
996    GGCGGGCCGCGCCCCCCTGAACGCTCCCCACTCTGCCGGCCCCGGCATCCCGGAGCCCCGTTCGGATAGCCGCGCCCCGCGGCGGCCGTCTAGCCGCCGAGGCCTGAAGCGGGGAAGCGTAAGCCGTGAAGCCCTTTGGCCCGAGGGAGGCGGGCTGCGCCCGTCGCTGAGATCTGCAGCCTGGGCAGCCTTGCCCCTGAGCCCGGGCCCTCGGGAGGCTTGGCGGCCGCGCGCTACGGGCGCAGGGCGCACCCCGCGCCCGCAGGCCGGACCGGGGGGGAGAGCCCCA
997    GCCCGAAGGGGCAGGCCGCCGGGGGGGGCGGCCCGCTGGGCGCGCGCTCCTGCGCGATGCCGCCGCCTAGCCGCACCGGGCGGGCGACACCGTCCTCCCGCGAGGCGCTGCCGAAGCCCCAGGCCCCCCTCCGGCGCCTAGGCGAGCCAGGTCGAGCCCCCCCCGCTTGAAGGCCCATTTGACTCGGAGCTAAGCTGGATTAAGGCCTCGCCCGCGGGCGGCCGTCCGTTGGACCAGAGAGCTGGCGCCCCCGCCTGCCGTGGCCCCAGCCGAGCGGCGCTGGGGGGGA
998    GCGCGGCTGGCCCCGGCTAACACGCCTACGAGCCGGGGCCGCGCGGCATTTGGCGCTCTGCCCGGCACCGGAGTGCCCTCCGCGAGCCCGGGCCGGCCCCTGGGCGCCGCCTGCGGCAAGGGCGCGCTGCCAGCCCGGCCCCGAGAGAGGGCCGCCCTGAAGAGCTCCGAGGAGCCCCGGGACGCGAGCTCCTTGCCCCGCCCCCCGGCCGGGGGTGCGGCGCAGCGGGCGTAAGAGGCGAGGTTCCCCCGGCGATGGGCCCTATCCAGGTCCCGAGGCTTGGCTCCAA
999    GGCGTTAGGCCGCAGTAAGCCTAGGGGGGCGGCCTGGCATCGCGGCCTGATGACCCCTCGACCCCCGCCCCCCAATTGGGGCGAGACCCGGGCCGAGCGCGCCGGTCTGCCCGGGCCCGAAGGGCCGAGCGCCCCCCCGGCCGCCGGCAGCGCTGCCTGAGGCGGGGCAAGCGCCGCGCTGGCGAGCTCCGCCCTCTAGCCCCGCCGGGCCGGGACGCTTCCGAGAGCAGGGCCGCCTCCTCGGCGCCTTGTTGGCGCAGGTGGGCGGACCGCCCAGCCTGCCGGAGAA
1000   GCGGCCTCCCCCTGGGCCGGCACCCGGGGCCCTGCGGCCGGAGGGGAGCTTGCGAGTTGCCAGCCGACCCCCCCGGGCGCGCGTTGATGAAAGGAGCCGGCCGGCGCCTAGGCGGGGGGGACCCATGTCTAGCCCAGCGCGCGGTCATGTTCCCTCGCGCAGGCTGAGGCGCCGCCGCCGCCGCCGGGCCGCGGAACTTAAGGAGGAGCGGCTGCCAGGGCTCGGAAGACTGCCCGAGCGCCGGCCCCCCCTCCCGGGCCCTGCAGCGGCCGCCCTCGAGCCCGCGCTA

In [73]:
# files almost have same length
print(nrow(d4)); print(nrow(d5)); print(nrow(d4)-nrow(d5))

[1] 173024
[1] 166826
[1] 6198

In [74]:
max(d4$POS); max(d5$POS, na.rm = TRUE); sum(is.na(d5$POS))

[1] 46679698

[1] 46674891

[1] 0

In [75]:
d4$ID <- paste0(d4$CHR, ":", d4$POS, ":",d4$REF, ":", d4$ALT)
d4$ID_flip <-  paste0(d4$CHR, ":", d4$POS, ":",d4$ALT, ":", d4$REF)
d5$ID <- paste0(d5$CHR, ":", d5$POS, ":",d5$REF, ":", d5$ALT)
d5$ID_flip <-  paste0(d5$CHR, ":", d5$POS, ":",d5$ALT, ":", d5$REF)

In [76]:
id4_uniq <- unique(d4$ID)
id4_flip_uniq <- unique(d4$ID_flip)
id5_uniq <- unique(d5$ID)
id5_flip_uniq <- unique(d5$ID_flip)

In [77]:
# How many unqiue alleles are in D4 versus D5?
print(length(id4_uniq)); print(length(id5_uniq))

[1] 11541
[1] 11161

In [51]:
# What alleles are different?
diff <- unique(setdiff(id4_uniq, id5_uniq))
overlap <- unique(intersect(id4_uniq, id5_uniq))
length(diff); length(overlap)

[1] 9650

[1] 1891

In [52]:
# What alleles are different if we flip over all D5 (ireggardless of strand)?
length(unique(setdiff(id4_uniq, id5_flip_uniq)))
length(unique(intersect(id4_uniq, id5_flip_uniq)))

[1] 1893

[1] 9648

In [78]:
# Are there duplicate alleles in S4
d4_uniq <- data.frame(id4_uniq, id4_flip_uniq)
d4_uniq$id_d4 <- d4_uniq$id4_uniq %in% d4$ID
d4_uniq$id_flip_d4 <- d4_uniq$id4_flip_uniq %in% d4$ID
n4 <- sum(rowSums(d4_uniq[,3:4]) == 2)
print(paste(n4, 'alleles exists as flipped and unflipped in s4'))

[1] "754 alleles exists as flipped and unflipped in s4"

In [79]:
# Are there duplicate alleles in S5
d5_uniq <- data.frame(id5_uniq, id5_flip_uniq)
d5_uniq$id_d5 <- d5_uniq$id5_uniq %in% d5$ID
d5_uniq$id_flip_d5 <- d5_uniq$id5_flip_uniq %in% d5$ID
n5 <- sum(rowSums(d5_uniq[,3:4]) == 2)
print(paste(n5, 'alleles exists as flipped and unflipped in s5'))

[1] "8 alleles exists as flipped and unflipped in s5"

In [80]:
# Let's remove the 754 alleles that exists in the flipped version
d4_clean <- d4[! (d4$ID %in% d4_uniq$id4_flip_uniq),]

# now it looks like they are matching!
nrow(d4_clean); nrow(d5)

[1] 160807

[1] 166826

In [81]:
# let's check indiiual variant counts
id4_clean <- unique(d4_clean$ID)
id5 <- unique(d5$ID)
length(id4_clean); length(id5)

# roughly the same number of sites.

[1] 10787

[1] 11161

In [82]:
# what sites are different and why?
s4_super_overlap <- sum(id4_uniq %in% id5_uniq | id4_flip_uniq %in% id5_uniq) 
s5_super_overlap <- sum(id5_uniq %in% id4_uniq | id5_flip_uniq %in% id4_uniq) 
paste(s4_super_overlap, '/', length(id4_uniq), ' of sites in S4 are in S5')
paste(s5_super_overlap, '/', length(id5_uniq), ' of sites in S4 are in S5')

[1] "11531 / 11541  of sites in S4 are in S5"

[1] "11159 / 11161  of sites in S4 are in S5"

In [6]:
# there are 20K unique variants in S4 file but only 5K unique variants in S5 file.

[1] 20806
[1] 5663

In [7]:
print(sum(id5_uniq %in% id4_uniq)); print(sum(id5_uniq %in% id4_flip_uniq))

[1] 833
[1] 4997

In [24]:
bad_boys <- id5_uniq[id5_uniq %in% id4_uniq & id5_uniq %in% id4_flip_uniq]
length(bad_boys)
bad_boys[1]

[1] 169

[1] "chr20:145514:G:GCAAA"

In [34]:
head(d5[d5$ID %in% "chr20:145514:G:GCAAA"])
head(d5[d5$ID_flip %in% "chr20:145514:G:GCAAA"])
head(d4[d4$ID %in% "chr20:145514:G:GCAAA"])
head(d4[d4$ID_flip %in% "chr20:145514:G:GCAAA"])

  ID                   CHR   POS    REF ALT   MAF     AF      AC     AN
1 chr20:145514:G:GCAAA chr20 145514 G   GCAAA 0.15559 0.84441 337146 399268
2 chr20:145514:G:GCAAA chr20 145514 G   GCAAA 0.15559 0.84441 337146 399268
3 chr20:145514:G:GCAAA chr20 145514 G   GCAAA 0.15559 0.84441 337146 399268
4 chr20:145514:G:GCAAA chr20 145514 G   GCAAA 0.15559 0.84441 337146 399268
5 chr20:145514:G:GCAAA chr20 145514 G   GCAAA 0.15559 0.84441 337146 399268
6 chr20:145514:G:GCAAA chr20 145514 G   GCAAA 0.15559 0.84441 337146 399268
  HWE      trio_id index switch switches ID_flip
1 0.925354  3      234   0      0        chr20:145514:GCAAA:G
2 0.925354  4      234   0      0        chr20:145514:GCAAA:G
3 0.925354  5      234   0      0        chr20:145514:GCAAA:G
4 0.925354  7      234   0      0        chr20:145514:GCAAA:G
5 0.925354 10      234   0      0        chr20:145514:GCAAA:G
6 0.925354 12      234   0      0        chr20:145514:GCAAA:G

  ID                   CHR   POS    REF   ALT MAF      AF       AC    AN
1 chr20:145514:GCAAA:G chr20 145514 GCAAA G   0.155544 0.155544 62103 399262
2 chr20:145514:GCAAA:G chr20 145514 GCAAA G   0.155544 0.155544 62103 399262
3 chr20:145514:GCAAA:G chr20 145514 GCAAA G   0.155544 0.155544 62103 399262
4 chr20:145514:GCAAA:G chr20 145514 GCAAA G   0.155544 0.155544 62103 399262
5 chr20:145514:GCAAA:G chr20 145514 GCAAA G   0.155544 0.155544 62103 399262
6 chr20:145514:GCAAA:G chr20 145514 GCAAA G   0.155544 0.155544 62103 399262
  HWE      trio_id index switch switches ID_flip
1 0.918568  3      235   0      0        chr20:145514:G:GCAAA
2 0.918568  4      235   0      0        chr20:145514:G:GCAAA
3 0.918568  5      235   0      0        chr20:145514:G:GCAAA
4 0.918568  7      235   0      0        chr20:145514:G:GCAAA
5 0.918568 10      235   0      0        chr20:145514:G:GCAAA
6 0.918568 12      235   0      0        chr20:145514:G:GCAAA

  ID                   CHR   POS    REF ALT   MAF      AF       AC     AN
1 chr20:145514:G:GCAAA chr20 145514 G   GCAAA 0.155587 0.844413 337191 399320
2 chr20:145514:G:GCAAA chr20 145514 G   GCAAA 0.155587 0.844413 337191 399320
3 chr20:145514:G:GCAAA chr20 145514 G   GCAAA 0.155587 0.844413 337191 399320
4 chr20:145514:G:GCAAA chr20 145514 G   GCAAA 0.155587 0.844413 337191 399320
5 chr20:145514:G:GCAAA chr20 145514 G   GCAAA 0.155587 0.844413 337191 399320
6 chr20:145514:G:GCAAA chr20 145514 G   GCAAA 0.155587 0.844413 337191 399320
  HWE      trio_id index switch switches ID_flip
1 0.932126  3      148   0      0        chr20:145514:GCAAA:G
2 0.932126  4      148   0      0        chr20:145514:GCAAA:G
3 0.932126  5      148   0      0        chr20:145514:GCAAA:G
4 0.932126  7      148   0      0        chr20:145514:GCAAA:G
5 0.932126 10      148   0      0        chr20:145514:GCAAA:G
6 0.932126 12      148   0      0        chr20:145514:GCAAA:G

  ID                   CHR   POS    REF   ALT MAF      AF       AC    AN
1 chr20:145514:GCAAA:G chr20 145514 GCAAA G   0.155547 0.155547 62112 399314
2 chr20:145514:GCAAA:G chr20 145514 GCAAA G   0.155547 0.155547 62112 399314
3 chr20:145514:GCAAA:G chr20 145514 GCAAA G   0.155547 0.155547 62112 399314
4 chr20:145514:GCAAA:G chr20 145514 GCAAA G   0.155547 0.155547 62112 399314
5 chr20:145514:GCAAA:G chr20 145514 GCAAA G   0.155547 0.155547 62112 399314
6 chr20:145514:GCAAA:G chr20 145514 GCAAA G   0.155547 0.155547 62112 399314
  HWE     trio_id index switch switches ID_flip
1 0.89832  3      149   0      0        chr20:145514:G:GCAAA
2 0.89832  4      149   0      0        chr20:145514:G:GCAAA
3 0.89832  5      149   0      0        chr20:145514:G:GCAAA
4 0.89832  7      149   0      0        chr20:145514:G:GCAAA
5 0.89832 10      149   0      0        chr20:145514:G:GCAAA
6 0.89832 12      149   0      0        chr20:145514:G:GCAAA

In [8]:
nooverlap <- d4[ ! ((d4$ID_flip %in% id5_uniq) | (d4$ID %in% id5_uniq)),]

In [9]:
# but there are 15k variants in the S4 file that is not present in the S5 file
length(unique(nooverlap$ID))

[1] 14986

In [10]:
sum(d5$ID %in% d4$ID)

[1] 11334

In [11]:
sum(d5$ID %in% d4$ID_flip)

[1] 80238

In [12]:
nrow(d4); nrow(d5)

[1] 303373

[1] 291220

In [13]:
cat_grep <- function(f, g) fread(cmd = paste("cat",f,"| grep", g))

In [15]:
d4t <- cat_grep('data/phased/wes_union_calls/200k/shapeit4/with_parents/ukb_eur_wes_union_calls_200k_chr20.trio', "TRIO")
d5t <- cat_grep('data/phased/wes_union_calls/200k/shapeit5/parents/ukb_wes_union_calls_200k_shapeit5_parents_chr20.trio', "TRIO")

In [17]:
head(d4t); head(d5t)

  # TRIO [2]Father [3]Mother [4]Child [5]nTested [6]nMendelian Errors
1 TRIO   3198027   1536567   1079534  3322       12
2 TRIO   2555570   3345127   2503898  3140        5
3 TRIO   2065411   4283321   2291527  3114        0
4 TRIO   3050457   1393856   3620172  3304        4
5 TRIO   3050457   1393856   4408960  3329        2
6 TRIO   2099849   2503352   1144246  2980        0
  [7]nSwitch [8]nSwitch (%)
1 9          0.27
2 8          0.25
3 2          0.06
4 8          0.24
5 5          0.15
6 4          0.13

  # TRIO [2]Father [3]Mother [4]Child [5]nTested [6]nMendelian Errors
1 TRIO   3198027   1536567   1079534  3192       12
2 TRIO   2555570   3345127   2503898  3007        5
3 TRIO   2065411   4283321   2291527  2984        0
4 TRIO   3050457   1393856   3620172  3164        4
5 TRIO   3050457   1393856   4408960  3189        2
6 TRIO   2099849   2503352   1144246  2870        0
  [7]nSwitch [8]nSwitch (%)
1 10         0.31
2  8         0.27
3  5         0.17
4  6         0.19
5  6         0.19
6  2         0.07

In [14]:
d <- fread("data/")

       ID     CHR    POS    REF    ALT    MAF    AF     AC     AN     HWE
1                    NA                   NA     NA     NA     NA     NA
2                    NA                   NA     NA     NA     NA     NA
3                    NA                   NA     NA     NA     NA     NA
4                    NA                   NA     NA     NA     NA     NA
5                    NA                   NA     NA     NA     NA     NA
6                    NA                   NA     NA     NA     NA     NA
7                    NA                   NA     NA     NA     NA     NA
8                    NA                   NA     NA     NA     NA     NA
9                    NA                   NA     NA     NA     NA     NA
10                   NA                   NA     NA     NA     NA     NA
11                   NA                   NA     NA     NA     NA     NA
12                   NA                   NA     NA     NA     NA     NA
13                   NA                   NA     NA     NA     NA     NA
14                   NA                   NA     NA     NA     NA     NA
15                   NA                   NA     NA     NA     NA     NA
16                   NA                   NA     NA     NA     NA     NA
17                   NA                   NA     NA     NA     NA     NA
18                   NA                   NA     NA     NA     NA     NA
19                   NA                   NA     NA     NA     NA     NA
20                   NA                   NA     NA     NA     NA     NA
21                   NA                   NA     NA     NA     NA     NA
22                   NA                   NA     NA     NA     NA     NA
23                   NA                   NA     NA     NA     NA     NA
24                   NA                   NA     NA     NA     NA     NA
25                   NA                   NA     NA     NA     NA     NA
26                   NA                   NA     NA     NA     NA     NA
27                   NA                   NA     NA     NA     NA     NA
28                   NA                   NA     NA     NA     NA     NA
29                   NA                   NA     NA     NA     NA     NA
30                   NA                   NA     NA     NA     NA     NA
<U+22EE> <U+22EE> <U+22EE> <U+22EE> <U+22EE> <U+22EE> <U+22EE> <U+22EE> <U+22EE> <U+22EE> <U+22EE>
202709               NA                   NA     NA     NA     NA     NA
202710               NA                   NA     NA     NA     NA     NA
202711               NA                   NA     NA     NA     NA     NA
202712               NA                   NA     NA     NA     NA     NA
202713               NA                   NA     NA     NA     NA     NA
202714               NA                   NA     NA     NA     NA     NA
202715               NA                   NA     NA     NA     NA     NA
202716               NA                   NA     NA     NA     NA     NA
202717               NA                   NA     NA     NA     NA     NA
202718               NA                   NA     NA     NA     NA     NA
202719               NA                   NA     NA     NA     NA     NA
202720               NA                   NA     NA     NA     NA     NA
202721               NA                   NA     NA     NA     NA     NA
202722               NA                   NA     NA     NA     NA     NA
202723               NA                   NA     NA     NA     NA     NA
202724               NA                   NA     NA     NA     NA     NA
202725               NA                   NA     NA     NA     NA     NA
202726               NA                   NA     NA     NA     NA     NA
202727               NA                   NA     NA     NA     NA     NA
202728               NA                   NA     NA     NA     NA     NA
202729               NA                   NA     NA     NA     NA     NA
202730               NA                   NA     NA     NA     NA     NA
202731               NA                   NA     NA     NA     NA     NA
202732               NA                   NA     NA     NA     NA     NA
202733               NA                   NA     NA     NA     NA     NA
202734               NA                   NA     NA     NA     NA     NA
202735               NA                   NA     NA     NA     NA     NA
202736               NA                   NA     NA     NA     NA     NA
202737               NA                   NA     NA     NA     NA     NA
202738               NA                   NA     NA     NA     NA     NA
       trio_id index  switch switches
1       1      61880   4     0
2      10      61880   2     0
3      43      61880   0     0
4      47      61880   3     0
5      61      61880   0     0
6      73      61880   0     0
7      74      61880   2     0
8      85      61880   1     0
9      87      61880   2     0
10      2      61893   0     0
11      3      61893   2     0
12      4      61893   2     0
13      9      61893  18     0
14     12      61893   0     0
15     14      61893   2     0
16     17      61893   2     0
17     22      61893   0     0
18     25      61893   0     0
19     29      61893   2     0
20     31      61893   1     0
21     36      61893   3     0
22     38      61893   4     0
23     39      61893   1     0
24     45      61893   2     0
25     51      61893   0     0
26     52      61893   3     0
27     59      61893   0     0
28     61      61893   0     0
29     62      61893   2     0
30     67      61893   6     0
<U+22EE> <U+22EE> <U+22EE> <U+22EE> <U+22EE>
202709 16      327072  3     0
202710 18      327072  0     0
202711 20      327072  3     0
202712 26      327072  3     0
202713 28      327072  2     0
202714 29      327072  4     0
202715 30      327072  8     0
202716 31      327072  5     0
202717 35      327072  6     0
202718 42      327072  5     0
202719 44      327072  0     0
202720 46      327072  3     0
202721 48      327072  4     0
202722 52      327072  5     0
202723 53      327072  2     0
202724 55      327072 34     0
202725 61      327072  4     0
202726 64      327072  6     0
202727 65      327072  3     0
202728 73      327072  4     0
202729 74      327072  2     0
202730 75      327072  6     0
202731 78      327072  0     0
202732 81      327072  2     0
202733 82      327072  2     0
202734 86      327072  0     0
202735 87      327072  3     0
202736 88      327072  0     0
202737 90      327072  4     0
202738 91      327072  6     0