In [1]:
library(data.table)
setwd("/well/lindgren-ukbb/projects/ukbb-11867/flassen/projects/KO/wes_ko_ukbb")

## First, let's check the DS (rowSums) of the original data:

In [61]:
path <- "data/knockouts/alt/ukb_eur_wes_200k_chr1_maf0to5e-2_pLoF_damaging_missense.tsv.gz" # ENSG00000132763

In [76]:
hashtags <- fread(cmd = "zcat data/knockouts/alt/ukb_eur_wes_200k_chr1_maf0to5e-2_pLoF_damaging_missense.vcf.bgz | grep \\# ")

Warning message in fread(cmd = "zcat data/knockouts/alt/ukb_eur_wes_200k_chr1_maf0to5e-2_pLoF_damaging_missense.vcf.bgz | grep \\# "):
"Detected 4 column names but the data has 2 columns. Filling rows automatically. Set fill=TRUE explicitly to avoid this warning."

In [135]:
header <- fread(cmd = "zcat data/knockouts/alt/ukb_eur_wes_200k_chr1_maf0to5e-2_pLoF_damaging_missense.vcf.bgz | grep CHR")
d <- fread(cmd = "zcat data/knockouts/alt/ukb_eur_wes_200k_chr1_maf0to5e-2_pLoF_damaging_missense.vcf.bgz | grep ENSG00000162654", colClasses=c("character"))
#d <- fread(cmd = "zcat data/knockouts/alt/ukb_eur_wes_200k_chr1_maf0to5e-2_pLoF_damaging_missense.vcf.bgz | grep ENSG00000162654")
header <- as.character(header[1,])

In [136]:
colnames(d) <- header

In [137]:
d

  #CHROM POS ID              REF ALT QUAL FILTER INFO FORMAT 1705888 <U+22EF>
1 chr1   1   ENSG00000162654 0   1   .    .      .    DS     0.00000 <U+22EF>
  4233598 5482567 4551958 2045144 3796382 3807442 4971879 5967795 4035219
1 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000
  2095689
1 0.00000

In [138]:
ncol(d)

[1] 176924

In [139]:
rowSums(d[1,10:ncol(d)])

ERROR: Error in rowSums(d[1, 10:ncol(d)]): 'x' must be numeric

In [ ]:
csums <- colSums(d[,10:ncol(d)])

In [ ]:
sum(d[,10:ncol(d)] == 0)

In [ ]:
# dosage for standard file
csums[csums > 0]

In [ ]:
dtmp <- d[,10:20]

In [ ]:
dtmp[dtmp == 0] <- 0.0000

In [ ]:
dtmp

In [140]:
final <- d

In [142]:
final

  #CHROM POS ID              REF ALT QUAL FILTER INFO FORMAT 1705888 <U+22EF>
1 chr1   1   ENSG00000162654 0   1   .    .      .    DS     0.00000 <U+22EF>
  4233598 5482567 4551958 2045144 3796382 3807442 4971879 5967795 4035219
1 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000
  2095689
1 0.00000

In [141]:
# let's write this file again
path_new_header <- "/well/lindgren-ukbb/projects/ukbb-11867/flassen/projects/KO/wes_ko_ukbb/data/permute/permutations/chrs/chr1/ENSG00000162654/ukb_eur_wes_200k_chr1_maf0to5e-2_pLoF_damaging_missense.header"
new_header <- readLines(path_new_header)

outfile <- "/well/lindgren-ukbb/projects/ukbb-11867/flassen/projects/KO/wes_ko_ukbb/data/permute/permutations/chrs/chr1/ENSG00000162654/original_re_written_only_characters.vcf"
writeLines(text = new_header,outfile)
fwrite(final, outfile, append = TRUE, quote = FALSE, sep = '\t', col.names = TRUE)

## Let's look at the rowSums for permuted data:

In [9]:
path_permuted <- "data/permute/permutations/chrs/chr1/ENSG00000162654/ukb_eur_wes_200k_pLoF_damaging_missense_permuted_chr1_ENSG00000162654_1.vcf.gz"
permuted_header <- fread(cmd = paste("zcat", path_permuted,"| grep CHR"))
permuted_header <- as.character(permuted_header[1,])
p <- fread(cmd = paste("zcat", path_permuted,"| grep ENSG00000162654"))
colnames(p) <- permuted_header

In [10]:
head(p, 1)

  #CHROM POS ID              REF ALT QUAL FILTER INFO FORMAT 1000028 <U+22EF>
1 chr1   1   ENSG00000162654 X   Y   .    .      .    DS     0       <U+22EF>
  6026237 6026268 6026270 6026295 6026311 6026322 6026335 6026383 6026397
1 0       0       0       0       0       0       0       0       0
  6026401
1 0

In [11]:
rowSums(p[1:10,10:ncol(p)])

 [1] 10 10 10 10 10 10 10 10 10 10

In [12]:
p <- head(p, 1)

In [13]:
sum(colnames(d) == colnames(p))

[1] 9

In [14]:
csums <- colSums(p[,10:ncol(p)])

In [15]:
# dosage for permuted file
csums[csums > 0]

1639563 1986042 2230893 2360859 2619778
      2       2       2       2       2

In [17]:
sum(p[,10:ncol(p)] == 0)

[1] 176910

In [19]:
print(all(colnames(p) %in% colnames(d)))
print(all(colnames(d) %in% colnames(p)))

[1] TRUE
[1] TRUE

**Takeaway:** rowSums are the same in both conditions. Same indiviudals are affected. So psuedo-variant encoding is correct. However, the sample order has been switch around. So per

In [24]:
# make header of VCF file
make_vcf_dosage_header <- function(chrom){
    vcf_format <- '##fileformat=VCFv4.2'
    vcf_entry <-  '##FORMAT=<ID=DS,Number=1,Type=Float,Description="">'
    vcf_filter <- '##FILTER=<ID=PASS,Description="All filters passed">"'
    vcf_contig <- paste0('##contig=<ID=',chrom,',length=81195210>')
    vcf_out <- paste(vcf_format, vcf_entry, vcf_filter, vcf_contig, sep = '\n')
    return(vcf_out)
}

In [69]:
d_first_cols <- colnames(d)[1:9]
d_last_cols <- colnames(d)[10:ncol(d)]
p_first_cols <- colnames(p)[1:9]
p_last_cols <- colnames(p)[10:ncol(p)]

p_new <- p[,c(d_first_cols,d_last_cols), with = FALSE]

In [70]:
p_new$REF <- '0'
p_new$ALT <- '1'

In [71]:
print(all(colnames(p_new) == colnames(d)))
print(all(p_new == d))

[1] TRUE
[1] TRUE

In [48]:
p_new[,which(p_new != d), with = FALSE]

  REF ALT
1 X   Y

In [93]:
which(d != p[1,])

 [1]      4      5  22525  34798  38417  43477  48063  57187  72417  87581
[11] 132099 170452

In [87]:
path_new_header <- "/well/lindgren-ukbb/projects/ukbb-11867/flassen/projects/KO/wes_ko_ukbb/data/permute/permutations/chrs/chr1/ENSG00000162654/ukb_eur_wes_200k_chr1_maf0to5e-2_pLoF_damaging_missense.header"
new_header <- readLines(path_new_header)

In [88]:
outfile = "/well/lindgren-ukbb/projects/ukbb-11867/flassen/projects/KO/wes_ko_ukbb/data/permute/permutations/chrs/chr1/ENSG00000162654/original_file_new_header.vcf"
final <- d

In [89]:
writeLines(text = new_header,outfile)
#writeLines(text = make_vcf_dosage_header("chr1"),outfile)
fwrite(final, outfile, append = TRUE, quote = FALSE, sep = '\t', col.names = TRUE)

In [9]:
pvalues <- "data/permute/permutations/chrs/chr1/ENSG00000162654/ukb_eur_wes_200k_pLoF_damaging_missense_permuted_chr1_ENSG00000162654.permuted"
d_pvalues <- fread(pvalues)
d_pvalues

  V1              V2                                V3   V4       V5 V6 V7
1 ENSG00000162654 Alanine_aminotransferase_residual 1000 0.387647 0  1  OK

In [18]:
list.files("data/permute/permutations/chrs/chr1/ENSG00000162654/")

 [1] "ENSG00000162654.errors.log"
 [2] "ENSG00000162654.log"
 [3] "saige.errors.log"
 [4] "saige.log"
 [5] "ukb_eur_wes_200k_pLoF_damaging_missense_permuted_chr1_ENSG00000162654.permuted"
 [6] "ukb_eur_wes_200k_pLoF_damaging_missense_permuted_chr1_ENSG00000162654.phenos"
 [7] "ukb_eur_wes_200k_pLoF_damaging_missense_permuted_chr1_ENSG00000162654.pvalues.txt.gz"
 [8] "ukb_eur_wes_200k_pLoF_damaging_missense_permuted_chr1_ENSG00000162654_1.vcf.gz"
 [9] "ukb_eur_wes_200k_pLoF_damaging_missense_permuted_chr1_ENSG00000162654_1.vcf.gz.csi"
[10] "ukb_eur_wes_200k_pLoF_damaging_missense_permuted_chr1_ENSG00000162654_Alanine_aminotransferase_residual_1.txt.gz"
[11] "ukb_eur_wes_200k_pLoF_damaging_missense_permuted_chr1_ENSG00000162654_Alanine_aminotransferase_residual_merged.txt.gz"

In [11]:
i = 1

In [21]:
path_saige <- list.files("data/permute/permutations/chrs/chr1/ENSG00000162654/", pattern = "1.txt.gz", full.names = TRUE)[i]
path_vcf <- list.files("data/permute/permutations/chrs/chr1/ENSG00000162654/", pattern = ".vcf.gz", full.names = TRUE)[i]

In [22]:
print(path_saige)
print(path_vcf)

[1] "data/permute/permutations/chrs/chr1/ENSG00000162654//ukb_eur_wes_200k_pLoF_damaging_missense_permuted_chr1_ENSG00000162654_Alanine_aminotransferase_residual_1.txt.gz"
[1] "data/permute/permutations/chrs/chr1/ENSG00000162654//ukb_eur_wes_200k_pLoF_damaging_missense_permuted_chr1_ENSG00000162654_1.vcf.gz"

In [23]:
saige <- fread(path_saige)

In [24]:
head(saige)

  CHR  POS MarkerID        Allele1 Allele2 AC_Allele2 AF_Allele2  MissingRate
1 chr1 1   ENSG00000162654 X       Y       10         3.00618e-05 0
2 chr1 2   ENSG00000162654 X       Y       10         3.00618e-05 0
3 chr1 3   ENSG00000162654 X       Y       10         3.00618e-05 0
4 chr1 4   ENSG00000162654 X       Y       10         3.00618e-05 0
5 chr1 5   ENSG00000162654 X       Y       10         3.00618e-05 0
6 chr1 6   ENSG00000162654 X       Y       10         3.00618e-05 0
  BETA         SE           Tstat   var          p.value N
1 -5.1419e+306 1.15351e+153 -3.8644 7.51552e-307 0       166324
2 -5.1419e+306 1.15351e+153 -3.8644 7.51552e-307 0       166324
3 -5.1419e+306 1.15351e+153 -3.8644 7.51552e-307 0       166324
4 -5.1419e+306 1.15351e+153 -3.8644 7.51552e-307 0       166324
5 -5.1419e+306 1.15351e+153 -3.8644 7.51552e-307 0       166324
6 -5.1419e+306 1.15351e+153 -3.8644 7.51552e-307 0       166324

In [25]:
table(saige$p.value)

   0
1000

In [26]:
path_vcf

[1] "data/permute/permutations/chrs/chr1/ENSG00000162654//ukb_eur_wes_200k_pLoF_damaging_missense_permuted_chr1_ENSG00000162654_1.vcf.gz"

In [27]:
header <- fread(cmd = paste("zcat",path_vcf,"| grep CHR"))
header <- as.character(header[1,])

In [ ]:
dt <- fread(cmd = paste("zcat",path_vcf,"| grep -v '#' | head -n 2000"))
colnames(dt) <- header
#dt <- dt[dt$POS == 3,]

In [ ]:
cols <- 10:ncol(dt)
sums <- rowSums(dt[,cols, with = FALSE])

In [ ]:
table(sums)

In [135]:

#for (i in 1:1){
#    indexes <- which(dt[1,cols, with = FALSE] != d[i,cols, with = FALSE])
#    print(rbind(
#        d[1,indexes, with = FALSE],
#        dt[1,indexes, with = FALSE]
#    ))
#}

In [136]:
head(dt)

  #CHROM POS ID              REF ALT QUAL FILTER INFO FORMAT 1000028 <U+22EF>
1 chr1   1   ENSG00000132763 X   Y   .    .      .    DS     0       <U+22EF>
2 chr1   2   ENSG00000132763 X   Y   .    .      .    DS     0       <U+22EF>
3 chr1   3   ENSG00000132763 X   Y   .    .      .    DS     0       <U+22EF>
4 chr1   4   ENSG00000132763 X   Y   .    .      .    DS     0       <U+22EF>
5 chr1   5   ENSG00000132763 X   Y   .    .      .    DS     0       <U+22EF>
6 chr1   6   ENSG00000132763 X   Y   .    .      .    DS     0       <U+22EF>
  6026237 6026268 6026270 6026295 6026311 6026322 6026335 6026383 6026397
1 0       0       0       0       0       0       0       0       0
2 0       0       0       0       0       0       0       0       0
3 0       0       0       0       0       0       0       0       0
4 0       0       0       0       0       0       0       0       0
5 0       0       0       0       0       0       0       0       0
6 0       0       0       0       0       0       0       0       0
  6026401
1 0
2 0
3 0
4 0
5 0
6 0

In [120]:
print(dim(dt))
print(dim(d))

[1]      1 176924
[1]      1 176924

In [121]:
#dim(d)[2] - sum(dt[1, ] == dt[2,])
#dim(d)[2] - sum(dt[1, ] == dt[3,])

In [122]:
all(dt == d)

[1] FALSE

In [123]:
dim(d)[2] - sum(dt == d)

[1] 10

In [124]:
indexes <- which(dt != d)

In [125]:
indexes

 [1]      2      4      5   8199  22979  58510  64122  99058 115957 119174

In [126]:
d[1,indexes, with = FALSE]

  POS REF ALT 3809313 2657939 3963610 3591973 2500336 2817220 1332879
1 1   0   1   2       2       0       0       0       2       0

In [127]:
dt[1,indexes, with = FALSE]

  POS REF ALT 1231017 1652888 2657939 2817220 3809313 4290441 4382702
1 3   X   Y   0       0       1       1       1       0       1

In [ ]:
path_permuted <- "data/permute/permutations/chrs/chr1/ENSG00000162654/ukb_eur_wes_200k_pLoF_damaging_missense_permuted_chr1_ENSG00000162654_1.vcf.gz"
path_og <- "data/"