In [36]:
setwd("/well/lindgren-ukbb/projects/ukbb-11867/flassen/projects/KO/wes_ko_ukbb")
library(devtools)
library(data.table)
library(reshape2)

devtools::load_all("utils/modules/R/phasingtools/")

Loading required package: usethis

i Loading phasingtools

Loading required package: ggplot2

Loading required package: Hmisc

Loading required package: lattice

Loading required package: survival

Loading required package: Formula


Attaching package: 'Hmisc'


The following objects are masked from 'package:base':

    format.pval, units


Loading required package: stringr

! Skipping missing files: /gpfs3/well/lindgren-ukbb/projects/ukbb-11867/flassen/projects/KO/wes_ko_ukbb/utils/modules/R/phasingtools/R/aggr_ser_by_site.R

! Adding files missing in collate: /gpfs3/well/lindgren-ukbb/projects/ukbb-11867/flassen/projects/KO/wes_ko_ukbb/utils/modules/R/phasingtools/R/aggr_ser_by_pos.R, /gpfs3/well/lindgren-ukbb/projects/ukbb-11867/flassen/projects/KO/wes_ko_ukbb/utils/modules/R/phasingtools/R/bp_betwen_single_switches.R, /gpfs3/well/lindgren-ukbb/projects/ukbb-11867/flassen/projects/KO/wes_ko_ukbb/utils/modules/R/phasingtools/R/eval_gt_agreement_by_bin.R, /gpfs3/well/lindgren-ukbb/projects/ukbb-11867/flassen/projects/KO/wes_ko_ukbb/utils/modules/R/phasingtools/R/extract_chunk_id.R, /gpfs3/well/lindgren-ukbb/projects/ukbb-11867/flassen/projects/KO/wes_ko_ukbb/utils/modules/R/phasingtools/R/fread_phased_sites.R, /gpfs3/well/lindgren-ukbb/projects/ukbb-11867/flassen/projects/KO/wes_ko_ukbb/utils/modules/R/phasingtools/R/get_switch_error_per_gene.R, /gpfs3/well/lindgren-ukbb/projects/ukbb-11867/flassen/projects/KO/wes_ko_ukbb/utils/modules/R/phasingtools/R/mirror_gt.R, and /gpfs3/well/lindgren-ukbb/projects/ukbb-11867/flassen/projects/KO/wes_ko_ukbb/utils/modules/R/phasingtools/R/read_chunks_from_dir.R

Warning message:
"
-- Conflicts ------------------------------------------------------------ phasingtools conflicts --
x eval_gt_agreement_by_bin() masks phasingtools::eval_gt_agreement_by_bin()

Did you accidentally source a file rather than using `load_all()`?
Run `rm(list = c("eval_gt_agreement_by_bin"))` to remove the conflicts."

In [ ]:
frea

In [2]:
args <- list(
    n_samples = 1000,
    pp_cutoff = 0.95,
    seed = 52,
    sites = "/well/lindgren/UKBIOBANK/dpalmer/wes_200k/ukb_wes_qc/data/variants/08_final_qc.keep.variant_list",
    mac_bin = "singleton",
    input_path = "data/prephased/wes_union_calls/phase_conf/ukb_shapeit5_whatshap_chr20.PP.PS.txt.gz",
    out_prefix = "test"

)

In [15]:
# get WES sites
n_samples <- as.numeric(args$n_samples)
pp_cutoff <- as.numeric(args$pp_cutoff)
seed <- as.numeric(args$seed)
sites <- args$sites
mac_bin <- args$mac_bin
input_path <- args$input_path
out_prefix <- args$out_prefix
stopifnot(file.exists(sites))
variants <- fread(sites)

# get phased fil
d <- fread(args$input_path)
stopifnot("MAC" %in% colnames(d))
stopifnot("PP" %in% colnames(d))
keep <- d$locus %in% variants$locus
d <- d[keep,]
d$MAC <- as.numeric(d$MAC)

# bins
bins <- c(0,1,5,10,20,50,100,200,500,1000,2000,5000,10000, Inf)

# keep phased sets with at least one rare variant
bool_keep <- (!is.na(d$PP) & d$MAC < (bins[length(bins)-1]+1))
ps_to_keep <- unique(d$PS_rb[bool_keep])
dt <- d[d$PS_rb %in% ps_to_keep,]
stopifnot(nrow(dt) > 0)

# use same bins as in S5 paper
labels <- unlist(lapply(2:length(bins), function(i){paste0(bins[i-1]+1,"-",bins[i])}))
labels[labels == '1-1'] <- "singleton"
dt$bin <- cut(dt$MAC, breaks = bins, labels = labels)

# ensure that selected mac_bin is available.
stopifnot(mac_bin %in% labels)
labels_to_run <- mac_bin

# NA's are due to well phased genotypes
dt$PP[is.na(dt$PP)] <- 1

In [49]:
n_samples <- 1000
set.seed(seed)
my_samples <- sample(unique(dt$s), n_samples, replace = FALSE)
dt_new <- dt[dt$s %in% my_samples,]

In [50]:
system.time({eval_gt_agreement_by_bin(dt_new, "201-500",pp_cutoff = 0.90, verbose =  TRUE) })

   user  system elapsed
134.267   6.151 140.847

ERROR: Error in time$elapsed: $ operator is invalid for atomic vectors

In [ ]:
"2-5" %in% dt_new$bin

In [37]:
eval_gt_agreement_by_bin <- function(dt, labels, pp_cutoff = NULL, verbose = TRUE){
    stopifnot("GT" %in% colnames(dt))
    stopifnot("GT_rb" %in% colnames(dt))
    stopifnot("GT_rb" %in% colnames(dt))
    stopifnot("PP" %in% colnames(dt)) # phasing quality from S5
    stopifnot("rsid" %in% colnames(dt))
    stopifnot("bin" %in% colnames(dt))
    stopifnot(all(labels %in% dt$bin))
    by_bin <- lapply(labels, function(lab){
        if (verbose) write(paste0("Evaluating label ", lab,".."), stderr())
        bool_rsid <-  dt$bin %in% lab
        if (!is.null(pp_cutoff)){
            stopifnot(pp_cutoff <= 1)
            bool_rsid <- bool_rsid & dt$PP >= pp_cutoff
        }
        variants <- unique(dt$rsid[bool_rsid])
        phased_sets <- unique(dt$PS_rb[dt$rsid %in% variants])
        by_ps <- lapply(phased_sets, function(ps){
            bool_sample <- (dt$PS_rb %in% ps)
            samples <- unique(dt$s[bool_sample])
            by_sample <- lapply(samples, function(sid){
                bool_ps_sid <- (dt$s %in% sid) & (dt$PS_rb %in% ps)
                dt_ps_sid <- dt[bool_ps_sid,]
                if (any(variants %in% dt_ps_sid$rsid) & (nrow(dt_ps_sid) == 2)){
                    gt_rb <- dt_ps_sid$GT_rb
                    gt_rb_mirror <- mirror_gt(dt_ps_sid$GT_rb)
                    gt <- dt_ps_sid$GT
                    match <- any(all(gt == gt_rb) | all(gt == gt_rb_mirror))
                    min_mac <- min(dt_ps_sid$MAC)
                    max_mac <- max(dt_ps_sid$MAC)
                    min_pp <- min(dt_ps_sid$PP, na.rm = TRUE)
                    max_pp <- max(dt_ps_sid$PP) # PP is NA for certain varaints
                    max_pp <- ifelse(is.na(max_pp), 1, max_pp)
                    idx_target <- which((dt_ps_sid$PP == min_pp) & (dt_ps_sid$MAC == min_mac))
                    idx_informative <- which((dt_ps_sid$PP == max_pp) & (dt_ps_sid$MAC == max_mac))
                    # if both informative and target SNP has same PP/MAC, randomly select
                    idx_target <- ifelse(length(idx_target)==1, idx_target, 1)
                    idx_informative <- ifelse(length(idx_informative)==1, idx_target, 2)
                    rsid_informative <- dt_ps_sid$rsid[idx_informative]
                    rsid_target <- dt_ps_sid$rsid[idx_target]
                    result <- data.frame(
                        sid = sid,
                        ps = ps,
                        rsid_max_pp = rsid_informative,
                        rsid_min_pp = rsid_target,
                        min_mac = min_mac,
                        max_mac = max_mac,
                        min_pp = min_pp,
                        max_pp = max_pp,
                        match = match,
                        bin = lab
                    )
                    if (nrow(result) > 1){
                        print(head(result))
                        stop("stopped")
                    }
                    return(result)
                }
            })
            by_sample <- do.call(rbind, by_sample)
            return(by_sample)
        })
        by_ps <- do.call(rbind, by_ps)
        return(by_ps)
    })
    final <- do.call(rbind, by_bin)
    return(final)
}

In [14]:
path <- "data/permute/genes/chr7/ukb_eur_wes_200k_pLoF_damaging_missense_chr7_ENSG00000164692.tsv.gz"

In [10]:
phased_calls_500k_command <- "bcftools query -l data/phased/calls/shapeit5/by_maf/ukb_phased_calls_500k_chr21.vcf.gz"

phased_calls_500k_command <- "bcftools query -l data/phased/calls/shapeit5/by_maf/ukb_phased_calls_500k_chr21.vcf.gz"
phased_calls_500k <- fread(cmd = command)
colnames(phased_calls_500k) <- "s"
overlap <- fread("data/unphased/overlap/ukb_calls_wes_samples.txt")

In [12]:
length(intersect(phased_calls_500k$s, overlap$s))

[1] 198857

In [13]:
199282 - 198857

[1] 425

In [15]:
d <- fread(path, tmpdir = "data/tmp/rtmp/")

In [16]:
shuffle_knockouts <- function(d){
    d$KO <- rbinom(n=nrow(d), size=1, prob = d$pTKO)
    d$pKO <- ifelse((d$KO == 1), 1,
             ifelse((d$phased_het == 1 & d$unphased_het > 0), 1 - 1*(1/2)^d$unphased_het,
             ifelse((d$phased_het == 0 & d$unphased_het > 1), 1 - 2*(1/2)^d$unphased_het, 0)))
    return(d$pKO)
}

In [17]:
n = 10

In [19]:
# where is 3717495 (0.5)
# where is 1365568 (0.5)
# where is 1466583 (0.5)
weird_samples <- c(3717495, 1365568, 1466583)

In [20]:
d[d$s %in% c(weird_samples)]

  gene_id         s       unphased_het phased_het hom_alt_n pTKO
1 ENSG00000164692 1365568 1            1          0         0
2 ENSG00000164692 1466583 2            0          0         0
3 ENSG00000164692 3717495 1            1          0         0

In [ ]:
#ENSG00000164692	6026401	0	0	0	0.0000e+00
#ENSG00000164692	1326715	0	2	0	5.0000e-01
#ENSG00000164692	1890022	0	2	0	5.0000e-01
#ENSG00000164692	2301892	0	2	0	5.0000e-01
#ENSG00000164692	2314440	0	2	0	5.0000e-01
#ENSG00000164692	5571743	0	2	0	5.0000e-01

# where is 3717495 (0.5)
# where is 1365568 (0.5)
# where is 1466583 (0.5)

In [50]:
reps <- replicate(n, shuffle_knockouts(d))
rownames(reps) <- d$s
reps <- data.table(t(reps))

In [57]:
mat <- reps[,colSums(reps) > 0, with = FALSE]
mat <- mat[rowSums(mat) == 5, ]
ok <- mat[["1326715"]] == 1 & 
      #mat[["1890022"]] == 0 & 
      #mat[["2301892"]] == 0 & 
      mat[["2314440"]] == 0 
mat[ok, ]

#melted_mat <- melt(mat)

       1326715 1365568 1466583 1702288 1890022 2301892 2314440 3717495 5571743
1      1       0.5     0.5     0.5     0       1       0       0.5     1
2      1       0.5     0.5     0.5     1       1       0       0.5     0
3      1       0.5     0.5     0.5     1       1       0       0.5     0
4      1       0.5     0.5     0.5     1       0       0       0.5     1
5      1       0.5     0.5     0.5     1       0       0       0.5     1
6      1       0.5     0.5     0.5     1       1       0       0.5     0
7      1       0.5     0.5     0.5     1       1       0       0.5     0
8      1       0.5     0.5     0.5     1       0       0       0.5     1
9      1       0.5     0.5     0.5     1       1       0       0.5     0
10     1       0.5     0.5     0.5     1       1       0       0.5     0
11     1       0.5     0.5     0.5     0       1       0       0.5     1
12     1       0.5     0.5     0.5     1       0       0       0.5     1
13     1       0.5     0.5     0.5     0       1       0       0.5     1
14     1       0.5     0.5     0.5     0       1       0       0.5     1
15     1       0.5     0.5     0.5     1       0       0       0.5     1
16     1       0.5     0.5     0.5     1       1       0       0.5     0
17     1       0.5     0.5     0.5     0       1       0       0.5     1
18     1       0.5     0.5     0.5     0       1       0       0.5     1
19     1       0.5     0.5     0.5     0       1       0       0.5     1
20     1       0.5     0.5     0.5     0       1       0       0.5     1
21     1       0.5     0.5     0.5     1       1       0       0.5     0
22     1       0.5     0.5     0.5     1       0       0       0.5     1
23     1       0.5     0.5     0.5     0       1       0       0.5     1
24     1       0.5     0.5     0.5     0       1       0       0.5     1
25     1       0.5     0.5     0.5     0       1       0       0.5     1
26     1       0.5     0.5     0.5     0       1       0       0.5     1
27     1       0.5     0.5     0.5     0       1       0       0.5     1
28     1       0.5     0.5     0.5     0       1       0       0.5     1
29     1       0.5     0.5     0.5     1       0       0       0.5     1
30     1       0.5     0.5     0.5     1       0       0       0.5     1
<U+22EE> <U+22EE> <U+22EE> <U+22EE> <U+22EE> <U+22EE> <U+22EE> <U+22EE> <U+22EE> <U+22EE>
67     1       0.5     0.5     0.5     1       0       0       0.5     1
68     1       0.5     0.5     0.5     1       0       0       0.5     1
69     1       0.5     0.5     0.5     1       1       0       0.5     0
70     1       0.5     0.5     0.5     0       1       0       0.5     1
71     1       0.5     0.5     0.5     0       1       0       0.5     1
72     1       0.5     0.5     0.5     1       0       0       0.5     1
73     1       0.5     0.5     0.5     1       1       0       0.5     0
74     1       0.5     0.5     0.5     1       0       0       0.5     1
75     1       0.5     0.5     0.5     1       0       0       0.5     1
76     1       0.5     0.5     0.5     0       1       0       0.5     1
77     1       0.5     0.5     0.5     1       1       0       0.5     0
78     1       0.5     0.5     0.5     1       1       0       0.5     0
79     1       0.5     0.5     0.5     1       1       0       0.5     0
80     1       0.5     0.5     0.5     0       1       0       0.5     1
81     1       0.5     0.5     0.5     1       0       0       0.5     1
82     1       0.5     0.5     0.5     0       1       0       0.5     1
83     1       0.5     0.5     0.5     0       1       0       0.5     1
84     1       0.5     0.5     0.5     1       1       0       0.5     0
85     1       0.5     0.5     0.5     1       0       0       0.5     1
86     1       0.5     0.5     0.5     0       1       0       0.5     1
87     1       0.5     0.5     0.5     0       1       0       0.5     1
88     1       0.5     0.5     0.5     1       1       0       0.5     0
89     1       0.5     0.5     0.5     1       1       0       0.5     0
90     1       0.5     0.5     0.5     0       1       0       0.5     1
91     1       0.5     0.5     0.5     1       1       0       0.5     0
92     1       0.5     0.5     0.5     0       1       0       0.5     1
93     1       0.5     0.5     0.5     0       1       0       0.5     1
94     1       0.5     0.5     0.5     0       1       0       0.5     1
95     1       0.5     0.5     0.5     0       1       0       0.5     1
96     1       0.5     0.5     0.5     1       1       0       0.5     0

In [52]:
#mat

       1326715 1365568 1466583 1702288 1890022 2301892 2314440 3717495 5571743
1      0       0.5     0.5     0.5     0       1       1       0.5     1
2      0       0.5     0.5     0.5     1       1       0       0.5     1
3      0       0.5     0.5     0.5     1       1       0       0.5     1
4      1       0.5     0.5     0.5     1       0       1       0.5     0
5      0       0.5     0.5     0.5     0       1       1       0.5     1
6      0       0.5     0.5     0.5     1       0       1       0.5     1
7      0       0.5     0.5     0.5     1       1       0       0.5     1
8      1       0.5     0.5     0.5     0       1       0       0.5     1
9      0       0.5     0.5     0.5     0       1       1       0.5     1
10     0       0.5     0.5     0.5     1       1       1       0.5     0
11     0       0.5     0.5     0.5     1       0       1       0.5     1
12     0       0.5     0.5     0.5     1       0       1       0.5     1
13     0       0.5     0.5     0.5     1       0       1       0.5     1
14     0       0.5     0.5     0.5     0       1       1       0.5     1
15     0       0.5     0.5     0.5     1       0       1       0.5     1
16     1       0.5     0.5     0.5     1       1       0       0.5     0
17     1       0.5     0.5     0.5     0       1       1       0.5     0
18     1       0.5     0.5     0.5     1       1       0       0.5     0
19     0       0.5     0.5     0.5     1       0       1       0.5     1
20     1       0.5     0.5     0.5     1       0       0       0.5     1
21     0       0.5     0.5     0.5     1       1       0       0.5     1
22     0       0.5     0.5     0.5     1       1       0       0.5     1
23     1       0.5     0.5     0.5     1       0       0       0.5     1
24     0       0.5     0.5     0.5     1       1       0       0.5     1
25     0       0.5     0.5     0.5     1       1       1       0.5     0
26     0       0.5     0.5     0.5     1       1       1       0.5     0
27     1       0.5     0.5     0.5     1       1       0       0.5     0
28     1       0.5     0.5     0.5     0       0       1       0.5     1
29     0       0.5     0.5     0.5     1       1       0       0.5     1
30     1       0.5     0.5     0.5     1       1       0       0.5     0
<U+22EE> <U+22EE> <U+22EE> <U+22EE> <U+22EE> <U+22EE> <U+22EE> <U+22EE> <U+22EE> <U+22EE>
269    0       0.5     0.5     0.5     1       1       1       0.5     0
270    0       0.5     0.5     0.5     1       1       1       0.5     0
271    1       0.5     0.5     0.5     0       0       1       0.5     1
272    1       0.5     0.5     0.5     0       1       1       0.5     0
273    1       0.5     0.5     0.5     0       1       0       0.5     1
274    0       0.5     0.5     0.5     0       1       1       0.5     1
275    1       0.5     0.5     0.5     0       1       1       0.5     0
276    0       0.5     0.5     0.5     1       1       1       0.5     0
277    1       0.5     0.5     0.5     0       0       1       0.5     1
278    1       0.5     0.5     0.5     0       0       1       0.5     1
279    1       0.5     0.5     0.5     0       0       1       0.5     1
280    1       0.5     0.5     0.5     1       1       0       0.5     0
281    1       0.5     0.5     0.5     1       1       0       0.5     0
282    1       0.5     0.5     0.5     0       0       1       0.5     1
283    1       0.5     0.5     0.5     0       1       0       0.5     1
284    0       0.5     0.5     0.5     0       1       1       0.5     1
285    0       0.5     0.5     0.5     1       1       0       0.5     1
286    0       0.5     0.5     0.5     1       0       1       0.5     1
287    1       0.5     0.5     0.5     1       1       0       0.5     0
288    1       0.5     0.5     0.5     0       1       0       0.5     1
289    1       0.5     0.5     0.5     0       1       0       0.5     1
290    0       0.5     0.5     0.5     1       1       0       0.5     1
291    1       0.5     0.5     0.5     0       1       0       0.5     1
292    1       0.5     0.5     0.5     0       1       0       0.5     1
293    0       0.5     0.5     0.5     1       1       1       0.5     0
294    1       0.5     0.5     0.5     0       0       1       0.5     1
295    0       0.5     0.5     0.5     1       0       1       0.5     1
296    1       0.5     0.5     0.5     0       1       1       0.5     0
297    1       0.5     0.5     0.5     0       0       1       0.5     1
298    1       0.5     0.5     0.5     1       1       0       0.5     0

In [9]:
p99 <- "data/permute/permutations/chr7/ENSG00000164692/ukb_eur_wes_200k_pLoF_damaging_missense_permuted_chr7_ENSG00000164692_99.vcf.gz"
p98 <- "data/permute/permutations/chr7/ENSG00000164692/ukb_eur_wes_200k_pLoF_damaging_missense_permuted_chr7_ENSG00000164692_98.vcf.gz"

In [10]:
d99 <- fread(p99, tmpdir = "data/tmp/rtmp/", skip = '##', nrows = 10)
d98 <- fread(p98, tmpdir = "data/tmp/rtmp/", skip = '##', nrows = 10)

In [13]:
d99[1,]
d98[1,]

  #CHROM POS ID              REF ALT QUAL FILTER INFO FORMAT 1000028 <U+22EF>
1 chr7   1   ENSG00000164692 X   Y   .    .      .    DS     0       <U+22EF>
  6026237 6026268 6026270 6026295 6026311 6026322 6026335 6026383 6026397
1 0       0       0       0       0       0       0       0       0
  6026401
1 0

  #CHROM POS ID              REF ALT QUAL FILTER INFO FORMAT 1000028 <U+22EF>
1 chr7   1   ENSG00000164692 X   Y   .    .      .    DS     0       <U+22EF>
  6026237 6026268 6026270 6026295 6026311 6026322 6026335 6026383 6026397
1 0       0       0       0       0       0       0       0       0
  6026401
1 0

In [89]:
head(d, 2)

  #CHROM POS ID              REF ALT QUAL FILTER INFO FORMAT 1000028 <U+22EF>
1 chr7   1   ENSG00000164692 X   Y   .    .      .    DS     0       <U+22EF>
2 chr7   2   ENSG00000164692 X   Y   .    .      .    DS     0       <U+22EF>
  6026237 6026268 6026270 6026295 6026311 6026322 6026335 6026383 6026397
1 0       0       0       0       0       0       0       0       0
2 0       0       0       0       0       0       0       0       0
  6026401
1 0
2 0

In [83]:
table(d$p.value)

0.653154 0.707262 0.723476 0.725199  0.80211 0.894845 0.903404 0.913869
   62506    62443    62469    62624    62550    62412    62833    62593
0.922451 0.968206 0.975673
   62163    62491    62413

In [77]:
fread()

  V1     V2  V3 V4  V5  V6   V7     V8   V9     V10     <U+22EF>   V161275
1 #CHROM POS ID REF ALT QUAL FILTER INFO FORMAT 1000028 <U+22EF> 5584149
  V161276 V161277 V161278 V161279 V161280 V161281 V161282 V161283 V161284
1 5584165 5584201 5584225 5584299 5584312 5584377 5584402 5584416 55

In [52]:
args <- list(
    phenotype_bin = "data/phenotypes/spiros_brava_phenotypes_binary_500k.tsv",
    directory = "data/prs/scores/"
)

In [64]:
print(args)
stopifnot(file.exists(args$phenotype_bin))
stopifnot(dir.exists(args$directory))


# Load polygenic risk scores
files <- list.files(args$directory, pattern = ".txt.gz", full.names = TRUE)
files <- files[!grepl("chrom",files)]
print(files)

# combine files
lst <- lapply(files, fread)
mrg <- Reduce(merge, lst)
mrg$eid <- mrg$sid

# read binary phenotypes
d_bin <- fread(args$phenotype_bin)
d_bin <- d_bin[d_bin$eid %in% mrg$eid,]
cols_bin <- colnames(d_bin)

# subset cols to binary
cols <- gsub("_pgs","",colnames(mrg))
cols <- cols[cols %in% cols_bin]
d_bin <- d_bin[,colnames(d_bin) %in% cols, with = FALSE]
dt <- merge(mrg, d_bin, by = 'eid')

# calculate AUC
cols <- cols[!cols %in% "eid"]

$phenotype_bin
[1] "data/phenotypes/spiros_brava_phenotypes_binary_500k.tsv"

$directory
[1] "data/prs/scores/"

  [1] "data/prs/scores//AD_combined_pgs.txt.gz"
  [2] "data/prs/scores//AD_combined_primary_care_pgs.txt.gz"
  [3] "data/prs/scores//AFR_int_pgs.txt.gz"
  [4] "data/prs/scores//AMRA_int_pgs.txt.gz"
  [5] "data/prs/scores//AUT_combined_pgs.txt.gz"
  [6] "data/prs/scores//AUT_combined_primary_care_pgs.txt.gz"
  [7] "data/prs/scores//Alanine_aminotransferase_residual_int_pgs.txt.gz"
  [8] "data/prs/scores//Albumin_residual_int_pgs.txt.gz"
  [9] "data/prs/scores//Alkaline_Phosphatase_residual_int_pgs.txt.gz"
 [10] "data/prs/scores//Apolipoprotein_A_residual_int_pgs.txt.gz"
 [11] "data/prs/scores//Apolipoprotein_B_residual_int_pgs.txt.gz"
 [12] "data/prs/scores//Aspartate_aminotransferase_residual_int_pgs.txt.gz"
 [13] "data/prs/scores//BC_combined_pgs.txt.gz"
 [14] "data/prs/scores//BC_combined_primary_care_pgs.txt.gz"
 [15] "data/prs/scores//BMI_imp_int_pgs.txt.gz"
 [16] "data/prs/scores//BMI_int_pgs.txt.gz"
 [17] "data/prs/scores//CAD_combined_pgs.txt.gz"
 [18] "data/prs/scores//CAD_combined_primary_care_pgs.txt.gz"
 [19] "data/prs/scores//CC_combined_pgs.txt.gz"
 [20] "data/prs/scores//CC_combined_primary_care_pgs.txt.gz"
 [21] "data/prs/scores//CD_combined_pgs.txt.gz"
 [22] "data/prs/scores//CD_combined_primary_care_pgs.txt.gz"
 [23] "data/prs/scores//CIRR_combined_pgs.txt.gz"
 [24] "data/prs/scores//CIRR_combined_primary_care_pgs.txt.gz"
 [25] "data/prs/scores//CLD_combined_pgs.txt.gz"
 [26] "data/prs/scores//CLD_combined_primary_care_pgs.txt.gz"
 [27] "data/prs/scores//COPD_combined_pgs.txt.gz"
 [28] "data/prs/scores//COPD_combined_primary_care_pgs.txt.gz"
 [29] "data/prs/scores//C_reactive_Protein_residual_int_pgs.txt.gz"
 [30] "data/prs/scores//Calcium_residual_int_pgs.txt.gz"
 [31] "data/prs/scores//Cholesterol_residual_int_pgs.txt.gz"
 [32] "data/prs/scores//Creatinine_Serum_residual_int_pgs.txt.gz"
 [33] "data/prs/scores//Creatinine_Urine_residual_int_pgs.txt.gz"
 [34] "data/prs/scores//Cystatin_C_Serum_residual_int_pgs.txt.gz"
 [35] "data/prs/scores//DEM_combined_pgs.txt.gz"
 [36] "data/prs/scores//DEM_combined_primary_care_pgs.txt.gz"
 [37] "data/prs/scores//DEP_combined_pgs.txt.gz"
 [38] "data/prs/scores//DEP_combined_primary_care_pgs.txt.gz"
 [39] "data/prs/scores//DM_T1D_pgs.txt.gz"
 [40] "data/prs/scores//DM_T2D_pgs.txt.gz"
 [41] "data/prs/scores//Direct_Bilirubin_residual_int_pgs.txt.gz"
 [42] "data/prs/scores//EP_combined_pgs.txt.gz"
 [43] "data/prs/scores//EP_combined_primary_care_pgs.txt.gz"
 [44] "data/prs/scores//Gamma_glutamyltransferase_residual_int_pgs.txt.gz"
 [45] "data/prs/scores//Glucose_residual_int_pgs.txt.gz"
 [46] "data/prs/scores//HAM_combined_pgs.txt.gz"
 [47] "data/prs/scores//HAM_combined_primary_care_pgs.txt.gz"
 [48] "data/prs/scores//HDL_Cholesterol_residual_int_pgs.txt.gz"
 [49] "data/prs/scores//HEM_combined_pgs.txt.gz"
 [50] "data/prs/scores//HEM_combined_primary_care_pgs.txt.gz"
 [51] "data/prs/scores//HYP_combined_pgs.txt.gz"
 [52] "data/prs/scores//HYP_combined_primary_care_pgs.txt.gz"
 [53] "data/prs/scores//HbA1c_residual_int_pgs.txt.gz"
 [54] "data/prs/scores//IBD_combined_pgs.txt.gz"
 [55] "data/prs/scores//IBD_combined_primary_care_pgs.txt.gz"
 [56] "data/prs/scores//IGF_1_residual_int_pgs.txt.gz"
 [57] "data/prs/scores//INF_combined_primary_care_pgs.txt.gz"
 [58] "data/prs/scores//LC_combined_pgs.txt.gz"
 [59] "data/prs/scores//LC_combined_primary_care_pgs.txt.gz"
 [60] "data/prs/scores//Lipoprotein_A_residual_int_pgs.txt.gz"
 [61] "data/prs/scores//Microalbumin_Urine_residual_int_pgs.txt.gz"
 [62] "data/prs/scores//NAFLD_combined_pgs.txt.gz"
 [63] "data/prs/scores//NAFLD_combined_primary_care_pgs.txt.gz"
 [64] "data/prs/scores//NASH_combined_pgs.txt.gz"
 [65] "data/prs/scores//NASH_combined_primary_care_pgs.txt.gz"
 [66] "data/prs/scores//Oestradiol_residual_int_pgs.txt.gz"
 [67] "data/prs/scores//POI_combined_primary_care_pgs.txt.gz"
 [68] "data/prs/scores//PRE_combined_pgs.txt.gz"
 [69] "data/prs/scores//PRE_combined_primary_care_pgs.txt.gz"
 [70] "data/prs/scores//PRO_combined_pgs.txt.gz"
 [71] "data/prs/scores//PRO_combined_primary_care_pgs.txt.gz"
 [72] "data/prs/scores//PSOR_combined_pgs.txt.gz"
 [73] "data/prs/scores//PSOR_combined_primary_care_pgs.txt.gz"
 [74] "data/prs/scores//Phosphate_residual_int_pgs.txt.gz"
 [75] "data/prs/scores//Potassium_Urine_residual_int_pgs.txt.gz"
 [76] "data/prs/scores//RF_acute_combined_pgs.txt.gz"
 [77] "data/prs/scores//RF_acute_combined_primary_care_pgs.txt.gz"
 [78] "data/prs/scores//RF_chronic_combined_pgs.txt.gz"
 [79] "data/prs/scores//RF_chronic_combined_primary_care_pgs.txt.gz"
 [80] "data/prs/scores//RF_combined_pgs.txt.gz"
 [81] "data/prs/scores//RF_combined_primary_care_pgs.txt.gz"
 [82] "data/prs/scores//SHBG_residual_int_pgs.txt.gz"
 [83] "data/prs/scores//STR_combined_pgs.txt.gz"
 [84] "data/prs/scores//STR_combined_primary_care_pgs.txt.gz"
 [85] "data/prs/scores//STR_hem_combined_pgs.txt.gz"
 [86] "data/prs/scores//STR_hem_combined_primary_care_pgs.txt.gz"
 [87] "data/prs/scores//STR_isc_combined_pgs.txt.gz"
 [88] "data/prs/scores//STR_isc_combined_primary_care_pgs.txt.gz"
 [89] "data/prs/scores//Sodium_Urine_residual_int_pgs.txt.gz"
 [90] "data/prs/scores//Testosterone_residual_int_pgs.txt.gz"
 [91] "data/prs/scores//Total_Bilirubin_residual_int_pgs.txt.gz"
 [92] "data/prs/scores//Total_Protein_residual_int_pgs.txt.gz"
 [93] "data/prs/scores//Triglyceride_residual_int_pgs.txt.gz"
 [94] "data/prs/scores//Urate_residual_int_pgs.txt.gz"
 [95] "data/prs/scores//Urea_residual_int_pgs.txt.gz"
 [96] "data/prs/scores//VAT_int_pgs.txt.gz"
 [97] "data/prs/scores//Vitamin_D_residual_int_pgs.txt.gz"
 [98] "data/prs/scores//WHR_adj_BMI_int_pgs.txt.gz"
 [99] "data/prs/scores//WHR_int_pgs.txt.gz"
[100] "data/prs/scores//body_fat_percentage_int_pgs.txt.gz"
[101] "data/prs/scores//hip_circumference_int_pgs.txt.gz"
[102] "data/prs/scores//spiro_abdominal_aortic_aneurysm_pgs.txt.gz"
[103] "data/prs/scores//spiro_abdominal_hernia_pgs.txt.gz"
[104] "data/prs/scores//spiro_acne_pgs.txt.gz"
[105] "data/prs/scores//spiro_actinic_keratosis_pgs.txt.gz"
[106] "data/prs/scores//spiro_acute_kidney_injury_pgs.txt.gz"
[107] "data/prs/scores//spiro_agranulocytosis_pgs.txt.gz"
[108] "data/prs/scores//spiro_alcohol_problems_pgs.txt.gz"
[109] "data/prs/scores//spiro_alcoholic_liver_disease_pgs.txt.gz"
[110] "data/prs/scores//spiro_allergic_and_chronic_rhinitis_pgs.txt.gz"
[111] "data/prs/scores//spiro_alopecia_areata_pgs.txt.gz"
[112] "data/prs/scores//spiro_anal_fissure_pgs.txt.gz"
[113] "data/prs/scores//spiro_angiodysplasia_of_colon_pgs.txt.gz"
[114] "data/prs/scores//spiro_ankylosing_spondylitis_pgs.txt.gz"
[115] "data/prs/scores//spiro_anorectal_fistula_pgs.txt.gz"
[116] "data/prs/scores//spiro_anorectal_prolapse_pgs.txt.gz"
[117] "data/prs/scores//spiro_anxiety_disorders_pgs.txt.gz"
[118] "data/prs/scores//spiro_appendicitis_pgs.txt.gz"
[119] "data/prs/scores//spiro_asbestosis_pgs.txt.gz"
[120] "data/prs/scores//spiro_aspiration_pneumonitis_pgs.txt.gz"
[121] "data/prs/scores//spiro_asthma_pgs.txt.gz"
[122] "data/prs/scores//spiro_atrial_fibrillation_pgs.txt.gz"
[123] "data/prs/scores//spiro_atrioventricular_block_complete_pgs.txt.gz"
[124] "data/prs/scores//spiro_autoimmune_liver_disease_pgs.txt.gz"
[125] "data/prs/scores//spiro_bacterial_diseases_pgs.txt.gz"
[126] "data/prs/scores//spiro_barretts_oesophagus_pgs.txt.gz"
[127] "data/prs/scores//spiro_bells_palsy_pgs.txt.gz"
[128] "data/prs/scores//spiro_benign_neoplasm_and_polyp_of_uterus_pgs.txt.gz"
[129] "data/prs/scores//spiro_benign_neoplasm_of_colon_rectum_anus_and_anal_canal_pgs.txt.gz"
[130] "data/prs/scores//spiro_benign_neoplasm_of_ovary_pgs.txt.gz"
[131] "data/prs/scores//spiro_benign_neoplasm_of_stomach_and_duodenum_pgs.txt.gz"
[132] "data/prs/scores//spiro_bipolar_affective_disorder_and_mania_pgs.txt.gz"
[133] "data/prs/scores//spiro_bronchiectasis_pgs.txt.gz"
[134] "data/prs/scores//spiro_carpal_tunnel_syndrome_pgs.txt.gz"
[135] "data/prs/scores//spiro_cataract_pgs.txt.gz"
[136] "data/prs/scores//spiro_cholangitis_pgs.txt.gz"
[137] "data/prs/scores//spiro_cholecystitis_pgs.txt.gz"
[138] "data/prs/scores//spiro_cholelithiasis_pgs.txt.gz"
[139] "data/prs/scores//spiro_chronic_sinusitis_pgs.txt.gz"
[140] "data/prs/scores//spiro_chronic_viral_hepatitis_pgs.txt.gz"
[141] "data/prs/scores//spiro_coeliac_disease_pgs.txt.gz"
[142] "data/prs/scores//spiro_congenital_malformations_of_cardiac_septa_pgs.txt.gz"
[143] "data/prs/scores//spiro_copd_pgs.txt.gz"
[144] "data/prs/scores//spiro_coronary_heart_disease_not_otherwise_specified_pgs.txt.gz"
[145] "data/prs/scores//spiro_crohns_disease_pgs.txt.gz"
[146] "data/prs/scores//spiro_delirium_not_induced_by_alcohol_and_other_psychoactive_substances_pgs.txt.gz"
[147] "data/prs/scores//spiro_dementia_pgs.txt.gz"
[148] "data/prs/scores//spiro_depression_pgs.txt.gz"
[149] "data/prs/scores//spiro_dermatitis_pgs.txt.gz"
[150] "data/prs/scores//spiro_diabetes_pgs.txt.gz"
[151] "data/prs/scores//spiro_diabetic_neurological_complications_pgs.txt.gz"
[152] "data/prs/scores//spiro_diabetic_ophthalmic_complications_pgs.txt.gz"
[153] "data/prs/scores//spiro_diaphragmatic_hernia_pgs.txt.gz"
[154] "data/prs/scores//spiro_dilated_cardiomyopathy_pgs.txt.gz"
[155] "data/prs/scores//spiro_disorders_of_autonomic_nervous_system_pgs.txt.gz"
[156] "data/prs/scores//spiro_diverticular_disease_of_intestine_pgs.txt.gz"
[157] "data/prs/scores//spiro_dysmenorrhoea_pgs.txt.gz"
[158] "data/prs/scores//spiro_ear_and_upper_respiratory_tract_infections_pgs.txt.gz"
[159] "data/prs/scores//spiro_end_stage_renal_disease_pgs.txt.gz"
[160] "data/prs/scores//spiro_endometrial_hyperplasia_and_hypertrophy_pgs.txt.gz"
[161] "data/prs/scores//spiro_endometriosis_pgs.txt.gz"
[162] "data/prs/scores//spiro_enthesopathies_and_synovial_disorders_pgs.txt.gz"
[163] "data/prs/scores//spiro_epilepsy_pgs.txt.gz"
[164] "data/prs/scores//spiro_erectile_dysfunction_pgs.txt.gz"
[165] "data/prs/scores//spiro_essential_tremor_pgs.txt.gz"
[166] "data/prs/scores//spiro_eye_infections_pgs.txt.gz"
[167] "data/prs/scores//spiro_fatty_liver_pgs.txt.gz"
[168] "data/prs/scores//spiro_female_genital_prolapse_pgs.txt.gz"
[169] "data/prs/scores//spiro_female_infertility_pgs.txt.gz"
[170] "data/prs/scores//spiro_fibromatoses_pgs.txt.gz"
[171] "data/prs/scores//spiro_folate_deficiency_anaemia_pgs.txt.gz"
[172] "data/prs/scores//spiro_fracture_of_hip_pgs.txt.gz"
[173] "data/prs/scores//spiro_fracture_of_wrist_pgs.txt.gz"
[174] "data/prs/scores//spiro_gastritis_and_duodenitis_pgs.txt.gz"
[175] "data/prs/scores//spiro_gastro_oesophageal_reflux_disease_pgs.txt.gz"
[176] "data/prs/scores//spiro_giant_cell_arteritis_pgs.txt.gz"
[177] "data/prs/scores//spiro_glaucoma_pgs.txt.gz"
[178] "data/prs/scores//spiro_glomerulonephritis_pgs.txt.gz"
[179] "data/prs/scores//spiro_gout_pgs.txt.gz"
[180] "data/prs/scores//spiro_haemangioma_any_site_pgs.txt.gz"
[181] "data/prs/scores//spiro_hearing_loss_pgs.txt.gz"
[182] "data/prs/scores//spiro_heart_failure_pgs.txt.gz"
[183] "data/prs/scores//spiro_hepatic_failure_pgs.txt.gz"
[184] "data/prs/scores//spiro_hiv_pgs.txt.gz"
[185] "data/prs/scores//spiro_hodgkin_lymphoma_pgs.txt.gz"
[186] "data/prs/scores//spiro_hydrocoele_pgs.txt.gz"
[187] "data/prs/scores//spiro_hyperparathyroidism_pgs.txt.gz"
[188] "data/prs/scores//spiro_hyperplasia_of_prostate_pgs.txt.gz"
[189] "data/prs/scores//spiro_hypertension_pgs.txt.gz"
[190] "data/prs/scores//spiro_hypertrophy_of_nasal_turbinates_pgs.txt.gz"
[191] "data/prs/scores//spiro_hypo_or_hyperthyroidism_pgs.txt.gz"
[192] "data/prs/scores//spiro_hyposplenism_pgs.txt.gz"
[193] "data/prs/scores//spiro_immunodeficiencies_pgs.txt.gz"
[194] "data/prs/scores//spiro_infection_of_bones_and_joints_pgs.txt.gz"
[195] "data/prs/scores//spiro_infection_of_liver_pgs.txt.gz"
[196] "data/prs/scores//spiro_infection_of_other_or_unspecified_genitourinary_system_pgs.txt.gz"
[197] "data/prs/scores//spiro_infection_of_skin_and_subcutaneous_tissues_pgs.txt.gz"
[198] "data/prs/scores//spiro_infections_of_other_or_unspecified_organs_pgs.txt.gz"
[199] "data/prs/scores//spiro_infections_of_the_digestive_system_pgs.txt.gz"
[200] "data/prs/scores//spiro_infections_of_the_heart_pgs.txt.gz"
[201] "data/prs/scores//spiro_intellectual_disability_pgs.txt.gz"
[202] "data/prs/scores//spiro_intervertebral_disc_disorders_pgs.txt.gz"
[203] "data/prs/scores//spiro_intracerebral_haemorrhage_pgs.txt.gz"
[204] "data/prs/scores//spiro_iron_deficiency_anaemia_pgs.txt.gz"
[205] "data/prs/scores//spiro_irritable_bowel_syndrome_pgs.txt.gz"
[206] "data/prs/scores//spiro_ischaemic_stroke_pgs.txt.gz"
[207] "data/prs/scores//spiro_keratitis_pgs.txt.gz"
[208] "data/prs/scores//spiro_left_bundle_branch_block_pgs.txt.gz"
[209] "data/prs/scores//spiro_leiomyoma_of_uterus_pgs.txt.gz"
[210] "data/prs/scores//spiro_leukaemia_pgs.txt.gz"
[211] "data/prs/scores//spiro_lichen_planus_pgs.txt.gz"
[212] "data/prs/scores//spiro_liver_fibrosis_sclerosis_and_cirrhosis_pgs.txt.gz"
[213] "data/prs/scores//spiro_lower_respiratory_tract_infections_pgs.txt.gz"
[214] "data/prs/scores//spiro_macular_degeneration_pgs.txt.gz"
[215] "data/prs/scores//spiro_male_infertility_pgs.txt.gz"
[216] "data/prs/scores//spiro_menorrhagia_and_polymenorrhoea_pgs.txt.gz"
[217] "data/prs/scores//spiro_migraine_pgs.txt.gz"
[218] "data/prs/scores//spiro_monoclonal_gammopathy_of_undetermined_significance_pgs.txt.gz"
[219] "data/prs/scores//spiro_motor_neuron_disease_pgs.txt.gz"
[220] "data/prs/scores//spiro_multiple_myeloma_and_malignant_plasma_cell_neoplasms_pgs.txt.gz"
[221] "data/prs/scores//spiro_multiple_sclerosis_pgs.txt.gz"
[222] "data/prs/scores//spiro_myasthenia_gravis_pgs.txt.gz"
[223] "data/prs/scores//spiro_mycoses_pgs.txt.gz"
[224] "data/prs/scores//spiro_myocardial_infarction_pgs.txt.gz"
[225] "data/prs/scores//spiro_nasal_polyp_pgs.txt.gz"
[226] "data/prs/scores//spiro_neuromuscular_dysfunction_of_bladder_pgs.txt.gz"
[227] "data/prs/scores//spiro_non_acute_cystitis_pgs.txt.gz"
[228] "data/prs/scores//spiro_nonrheumatic_aortic_valve_disorders_pgs.txt.gz"
[229] "data/prs/scores//spiro_nonrheumatic_mitral_valve_disorders_pgs.txt.gz"
[230] "data/prs/scores//spiro_obesity_pgs.txt.gz"
[231] "data/prs/scores//spiro_obsessive_compulsive_disorder_pgs.txt.gz"
[232] "data/prs/scores//spiro_oesophageal_varices_pgs.txt.gz"
[233] "data/prs/scores//spiro_oesophagitis_and_oesophageal_ulcer_pgs.txt.gz"
[234] "data/prs/scores//spiro_osteoarthritis_pgs.txt.gz"
[235] "data/prs/scores//spiro_osteoporosis_pgs.txt.gz"
[236] "data/prs/scores//spiro_other_anaemias_pgs.txt.gz"
[237] "data/prs/scores//spiro_other_cardiomyopathy_pgs.txt.gz"
[238] "data/prs/scores//spiro_other_haemolytic_anaemias_pgs.txt.gz"
[239] "data/prs/scores//spiro_other_interstitial_pulmonary_diseases_with_fibrosis_pgs.txt.gz"
[240] "data/prs/scores//spiro_other_or_unspecified_infectious_organisms_pgs.txt.gz"
[241] "data/prs/scores//spiro_other_psychoactive_substance_misuse_pgs.txt.gz"
[242] "data/prs/scores//spiro_pancreatitis_pgs.txt.gz"
[243] "data/prs/scores//spiro_parasitic_infections_pgs.txt.gz"
[244] "data/prs/scores//spiro_parkinsons_disease_pgs.txt.gz"
[245] "data/prs/scores//spiro_peptic_ulcer_disease_pgs.txt.gz"
[246] "data/prs/scores//spiro_pericardial_effusion_pgs.txt.gz"
[247] "data/prs/scores//spiro_peripheral_arterial_disease_pgs.txt.gz"
[248] "data/prs/scores//spiro_peripheral_neuropathies_pgs.txt.gz"
[249] "data/prs/scores//spiro_peritonitis_pgs.txt.gz"
[250] "data/prs/scores//spiro_personality_disorders_pgs.txt.gz"
[251] "data/prs/scores//spiro_pilonidal_cyst_sinus_pgs.txt.gz"
[252] "data/prs/scores//spiro_pleural_effusion_pgs.txt.gz"
[253] "data/prs/scores//spiro_pleural_plaque_pgs.txt.gz"
[254] "data/prs/scores//spiro_polycythaemia_vera_pgs.txt.gz"
[255] "data/prs/scores//spiro_portal_hypertension_pgs.txt.gz"
[256] "data/prs/scores//spiro_postcoital_and_contact_bleeding_pgs.txt.gz"
[257] "data/prs/scores//spiro_postinfective_and_reactive_arthropathies_pgs.txt.gz"
[258] "data/prs/scores//spiro_postviral_fatigue_syndrome_neurasthenia_and_fibromyalgia_pgs.txt.gz"
[259] "data/prs/scores//spiro_prematurity_pgs.txt.gz"
[260] "data/prs/scores//spiro_primary_malignancy_biliary_tract_pgs.txt.gz"
[261] "data/prs/scores//spiro_primary_malignancy_bladder_pgs.txt.gz"
[262] "data/prs/scores//spiro_primary_malignancy_brain_other_cns_and_intracranial_pgs.txt.gz"
[263] "data/prs/scores//spiro_primary_malignancy_breast_pgs.txt.gz"
[264] "data/prs/scores//spiro_primary_malignancy_cervical_pgs.txt.gz"
[265] "data/prs/scores//spiro_primary_malignancy_colorectal_and_anus_pgs.txt.gz"
[266] "data/prs/scores//spiro_primary_malignancy_liver_pgs.txt.gz"
[267] "data/prs/scores//spiro_primary_malignancy_malignant_melanoma_pgs.txt.gz"
[268] "data/prs/scores//spiro_primary_malignancy_mesothelioma_pgs.txt.gz"
[269] "data/prs/scores//spiro_primary_malignancy_oesophageal_pgs.txt.gz"
[270] "data/prs/scores//spiro_primary_malignancy_oro_pharyngeal_pgs.txt.gz"
[271] "data/prs/scores//spiro_primary_malignancy_other_skin_and_subcutaneous_tissue_pgs.txt.gz"
[272] "data/prs/scores//spiro_primary_malignancy_ovarian_pgs.txt.gz"
[273] "data/prs/scores//spiro_primary_malignancy_pancreatic_pgs.txt.gz"
[274] "data/prs/scores//spiro_primary_malignancy_prostate_pgs.txt.gz"
[275] "data/prs/scores//spiro_primary_malignancy_stomach_pgs.txt.gz"
[276] "data/prs/scores//spiro_primary_malignancy_testicular_pgs.txt.gz"
[277] "data/prs/scores//spiro_primary_malignancy_thyroid_pgs.txt.gz"
[278] "data/prs/scores//spiro_primary_malignancy_uterine_pgs.txt.gz"
[279] "data/prs/scores//spiro_primary_or_idiopathic_thrombocytopaenia_pgs.txt.gz"
[280] "data/prs/scores//spiro_primary_pulmonary_hypertension_pgs.txt.gz"
[281] "data/prs/scores//spiro_psoriasis_pgs.txt.gz"
[282] "data/prs/scores//spiro_psoriatic_arthropathy_pgs.txt.gz"
[283] "data/prs/scores//spiro_ptosis_of_eyelid_pgs.txt.gz"
[284] "data/prs/scores//spiro_pulmonary_collapse_pgs.txt.gz"
[285] "data/prs/scores//spiro_pulmonary_embolism_pgs.txt.gz"
[286] "data/prs/scores//spiro_raynauds_syndrome_pgs.txt.gz"
[287] "data/prs/scores//spiro_respiratory_failure_pgs.txt.gz"
[288] "data/prs/scores//spiro_retinal_detachments_and_breaks_pgs.txt.gz"
[289] "data/prs/scores//spiro_retinal_vascular_occlusions_pgs.txt.gz"
[290] "data/prs/scores//spiro_rheumatic_fever_pgs.txt.gz"
[291] "data/prs/scores//spiro_rheumatoid_arthritis_pgs.txt.gz"
[292] "data/prs/scores//spiro_right_bundle_branch_block_pgs.txt.gz"
[293] "data/prs/scores//spiro_rosacea_pgs.txt.gz"
[294] "data/prs/scores//spiro_sarcoidosis_pgs.txt.gz"
[295] "data/prs/scores//spiro_schizophrenia_schizotypal_and_delusional_disorders_pgs.txt.gz"
[296] "data/prs/scores//spiro_scleritis_and_episcleritis_pgs.txt.gz"
[297] "data/prs/scores//standing_height_int_pgs.txt.gz"
[298] "data/prs/scores//waist_circumference_int_pgs.txt.gz"

In [57]:
x1 <- "spiro_diabetes"
x2 <- "DM_T2D"

In [61]:
col <- x2
write(paste("calculating auc for", col), stderr())
col_pgs <- paste0(col,'_pgs')
boot <- dt[,colnames(dt) %in% c('eid',col,col_pgs), with = FALSE]
boot <- boot[!is.na(boot[[col]]) & !is.na(boot[[col_pgs]]),]

In [63]:
boot

       eid     DM_T2D_pgs DM_T2D
1      1000028 0          FALSE
2      1000034 0          FALSE
3      1000087 0          FALSE
4      1000118 0          FALSE
5      1000120 0          FALSE
6      1000171 0          FALSE
7      1000196 0          FALSE
8      1000254 0          FALSE
9      1000278 0          FALSE
10     1000297 0          FALSE
11     1000302 0          FALSE
12     1000329 0          FALSE
13     1000337 0          FALSE
14     1000353 0          FALSE
15     1000370 0          FALSE
16     1000406 0           TRUE
17     1000427 0          FALSE
18     1000465 0          FALSE
19     1000473 0          FALSE
20     1000488 0          FALSE
21     1000508 0          FALSE
22     1000566 0          FALSE
23     1000579 0          FALSE
24     1000582 0          FALSE
25     1000600 0          FALSE
26     1000617 0          FALSE
27     1000624 0          FALSE
28     1000636 0          FALSE
29     1000648 0          FALSE
30     1000689 0          FALSE
<U+22EE> <U+22EE> <U+22EE>   <U+22EE>
161942 6025630 0          FALSE
161943 6025665 0          FALSE
161944 6025692 0          FALSE
161945 6025812 0          FALSE
161946 6025864 0          FALSE
161947 6025898 0          FALSE
161948 6025901 0           TRUE
161949 6025913 0          FALSE
161950 6025938 0          FALSE
161951 6025942 0          FALSE
161952 6025967 0          FALSE
161953 6025980 0          FALSE
161954 6025999 0          FALSE
161955 6026004 0          FALSE
161956 6026018 0          FALSE
161957 6026128 0          FALSE
161958 6026152 0          FALSE
161959 6026187 0          FALSE
161960 6026202 0          FALSE
161961 6026229 0          FALSE
161962 6026237 0          FALSE
161963 6026268 0          FALSE
161964 6026270 0          FALSE
161965 6026295 0          FALSE
161966 6026311 0          FALSE
161967 6026322 0          FALSE
161968 6026335 0          FALSE
161969 6026383 0          FALSE
161970 6026397 0          FALSE
161971 6026401 0          FALSE

In [ ]:
auc <- AUCBoot(
    pred = boot[[col_pgs]],
    target = as.numeric(boot[[col]]),
    nboot = 1000,
    seed = 1995
)

cases <- sum(boot[[col]]==1)
controls <- sum(boot[[col]]==0)
boot <- data.table(t(auc))
colnames(boot) <- paste0("auc_",tolower(colnames(boot)))
colnames(boot) <- gsub("\\%","_pct", colnames(boot))
colnames(boot) <- gsub("\\.","_", colnames(boot))
boot$pred_cases <- cases
boot$pred_controls <- controls
boot$pred_n <- cases + controls
boot$phenotype <- col