In [2]:
path = '../data/conditional/common/211111_spa_conditional_synonymous_breast_cancer_i1.txt'

In [6]:
d <- read.table(path)

In [7]:
d[duplicated(d),]

  V1  V2  V3    V4      V5      V6         V7         V8             V9 V10
2 CHR POS SNPID Allele1 Allele2 AC_Allele2 AF_Allele2 imputationInfo N  BETA
  <U+22EF>   V16  V17      V18      V19         V20     V21
2 <U+22EF> varT varTstar AF.Cases AF.Controls N.Cases N.Controls
  V22                V23                V24                V25
2 homN_Allele2_cases hetN_Allele2_cases homN_Allele2_ctrls hetN_Allele2_ctrls

In [8]:
sum(duplicated(d))

[1] 1

In [128]:
rep(NA, length(conds))

[1] NA NA NA NA NA

In [126]:
# collect all chromosomal outputs
prefix = '../data/conditional/common/211111_spa_conditional_synonymous_breast_cancer_i1'
files = list.files(dirname(prefix), pattern = basename(prefix), full.names = TRUE)
files_chr = files[grepl('chr', files)]

# combine into single table
d <- do.call(rbind, lapply(files_chr, fread))

# if cond_p col does not exist, add empty columns
conds = c('Tstat_cond','p.value_cond','varT_cond','BETA_cond','SE_cond')


#if (!all(conds %in% colnames(d))){
#    
#    ndf = as.data.frame(t(matrix(conds)))
#    colnames(ndf) <- ndf
#    ndf[1,] <- NA
#    d <- cbind(d, ndf)
#}

# re-organize columns in table (relevant for interations>1)
d <- cbind(
    d[,-conds, with = FALSE],
    d[,conds, with = FALSE]
)

# Select P-value
conditioning = all(is.na(d$p.value.cond)) & all(is.na(d$p.value))
write(paste0('Conditioning markers included: ', conditioning),stdout())
d$Tstat_new = unlist(ifelse(conditioning, list(d$Tstat_cond), list(d$Tstat)))
d$p.value_new = unlist(ifelse(conditioning, list(d$p.value_cond), list(d$p.value)))

# save combined table
d <- d[order(d$p.value_new)]
d

Conditioning markers included: FALSE

       CHR    POS      SNPID         Allele1 Allele2 AC_Allele2 AF_Allele2
1      chr6   31122301 rs6913137     G       T       111719.48  0.9007020
2      chr6   31119283 rs13201757    T       C       111904.35  0.9021925
3      chr6   31284147 rs12189871    T       C       113176.64  0.9124500
4      chr6   31321937 rs28894993    T       G       113090.59  0.9117562
5      chr6   31125413 rs6909321     A       G       112472.71  0.9067748
6      chr6   31127026 rs17196961    T       G       112483.30  0.9068601
7      chr6   31274954 rs12199223    A       T       113317.47  0.9135853
8      chr6   31126343 rs3778640     C       G       112418.20  0.9063353
9      chr6   31348922 rs28732138    A       G       113176.14  0.9124459
10     chr6   31127226 rs6931921     C       G       112739.16  0.9089230
11     chr6   31344018 rs28380862    A       C       101213.66  0.8160023
12     chr6   31392612 rs2523477     C       T       113060.99  0.9115176
13     chr6   32579135 rs34252386    AG      A        80555.86  0.6494554
14     chr6   31129275 rs9501055     A       G       105640.32  0.8516908
15     chr6   31133165 rs3823418     A       G       105567.76  0.8511058
16     chr6   31133624 rs4084091     T       C       105596.89  0.8513407
17     chr6   31133425 rs7743435     C       T       105651.20  0.8517785
18     chr6   32617723 rs28383249    T       C       105929.73  0.8540241
19     chr6   32641261 rs28383438    T       C       106210.65  0.8562889
20     chr6   31400811 rs2844523     A       G       113192.01  0.9125738
21     chr6   31133224 rs3823419     A       G       105678.98  0.8520025
22     chr6   31131180 rs13200022    T       C       105596.75  0.8513396
23     chr6   32466572 rs9268969     T       C        79790.20  0.6432826
24     chr6   32775326 rs2857208     C       T       112832.88  0.9096785
25     chr6   32598202 rs28383172    G       A       105811.73  0.8530727
26     chr6   32606237 rs2647073     C       A       105780.57  0.8528215
27     chr6   32465058 rs9268923     T       C        79773.80  0.6431504
28     chr6   32461866 rs9268853     C       T        79700.95  0.6425630
29     chr6   31970635 Affx-28465086 T       G       114332.88  0.9217718
30     chr6   31382377 rs2523547     T       C       113146.84  0.9122097
<U+22EE> <U+22EE> <U+22EE> <U+22EE>      <U+22EE> <U+22EE> <U+22EE>   <U+22EE>
3965   chr6   32443949 rs3129888     A       G        24136.91  0.1945960
3966   chr6   31289848 rs2524040     C       T        52435.98  0.4227481
3967   chr6   31307930 rs1619716     A       G       120941.45  0.9750512
3968   chr6   31041639 Affx-28439662 T       C       122412.90  0.9869143
3969   chr6   31729781 rs707916      A       G        79653.25  0.6421785
3970   chr6   32179984 rs3134943     C       T        18659.51  0.1504363
3971   chr6   31142894 rs1265085     C       G        99316.69  0.8007085
3972   chr6   31764104 rs6905572     T       C       109985.59  0.8867231
3973   chr6   31476133 rs9267156     T       A       114799.96  0.9255374
3974   chr6   31046528 rs9262582     A       C       112020.28  0.9031272
3975   chr6   31745347 rs3749953     G       A       109735.63  0.8847079
3976   chr6   32819140 rs3763354     A       G        28106.46  0.2265992
3977   chr6   31650984 rs3130050     A       G        19015.60  0.1533071
3978   chr6   31347004 rs2507997     G       A        85715.73  0.6910552
3979   chr6   31452100 rs2516436     G       C        57936.03  0.4670905
3980   chr6   31425129 rs2524279     G       A       116181.68  0.9366771
3981   chr6   31879859 rs41267086    A       G       117796.48  0.9496959
3982   chr6   31032220 rs10947121    C       T        81373.64  0.6560486
3983   chr6   31329460 rs78745236    G       A       122636.46  0.9887167
3984   chr6   31061481 rs2517515     T       C       105345.33  0.8493125
3985   chr6   31386727 rs4711268     T       C        96639.17  0.7791219
3986   chr6   31736288 rs147567766   G       GTTC    119241.36  0.9613447
3987   chr6   31392478 rs7751505     C       A        96591.39  0.7787368
3988   chr6   32445540 rs2395182     T       G        25968.12  0.2093596
3989   chr6   31392656 rs7751725     G       A        96761.47  0.7801079
3990   chr6   31947367 rs4151669     A       G       118528.47  0.9555973
3991   chr6   31533232 rs77689490    C       G       108670.95  0.8761243
3992   chr6   30924744 rs2532941     A       G        34267.81  0.2762731
3993   chr6   32194782 rs45592033    G       A       119151.41  0.9606196
3994   chr6   31468214 rs2523676     T       C       100835.66  0.8129547
       imputationInfo N      BETA          <U+22EF>   hetN_Allele2_cases
1      1              62018  -0.14536581   <U+22EF> 1110
2      1              62018  -0.14276275   <U+22EF> 1090
3      1              62018  -0.14447524   <U+22EF>  994
4      1              62018  -0.14194233   <U+22EF>  997
5      1              62018  -0.13812783   <U+22EF> 1042
6      1              62018  -0.13795391   <U+22EF> 1043
7      1              62018  -0.14339091   <U+22EF>  944
8      1              62018  -0.13507562   <U+22EF> 1039
9      1              62018  -0.13674870   <U+22EF>  967
10     1              62018  -0.13552795   <U+22EF> 1015
11     1              62018  -0.08907917   <U+22EF> 1772
12     1              62018  -0.11645042   <U+22EF>  984
13     1              62018  -0.07015368   <U+22EF> 2833
14     1              62018  -0.09111654   <U+22EF> 1500
15     1              62018  -0.09079719   <U+22EF> 1502
16     1              62018  -0.08994753   <U+22EF> 1502
17     1              62018  -0.09088166   <U+22EF> 1465
18     1              62018  -0.09017114   <U+22EF> 1509
19     1              62018  -0.09085274   <U+22EF> 1425
20     1              62018  -0.11168977   <U+22EF>  973
21     1              62018  -0.08913340   <U+22EF> 1500
22     1              62018  -0.08851478   <U+22EF> 1502
23     1              62018  -0.06547504   <U+22EF> 2699
24     1              62018  -0.10872795   <U+22EF> 1026
25     1              62018  -0.08803297   <U+22EF> 1512
26     1              62018  -0.08786261   <U+22EF> 1505
27     1              62018  -0.06485965   <U+22EF> 2705
28     1              62018  -0.06497285   <U+22EF> 2734
29     1              62018  -0.11501810   <U+22EF>  894
30     1              62018  -0.10875785   <U+22EF>  976
<U+22EE> <U+22EE>       <U+22EE> <U+22EE>      <U+22F1> <U+22EE>
3965   1              62018  -3.341141e-04 <U+22EF> 1771
3966   1              62018  -2.756423e-04 <U+22EF> 3030
3967   1              62018   8.254563e-04 <U+22EF>  276
3968   1              62018  -1.089883e-03 <U+22EF>  149
3969   1              62018   2.575761e-04 <U+22EF> 2591
3970   1              62018   3.414983e-04 <U+22EF> 1471
3971   1              62018   2.852661e-04 <U+22EF> 1778
3972   1              62018  -3.570071e-04 <U+22EF> 1135
3973   1              62018  -4.219323e-04 <U+22EF>  807
3974   1              62018   3.659474e-04 <U+22EF>  998
3975   1              62018  -3.334401e-04 <U+22EF> 1156
3976   1              62018  -2.479864e-04 <U+22EF> 2021
3977   1              62018   2.623079e-04 <U+22EF> 1481
3978   1              62018  -2.053026e-04 <U+22EF> 2487
3979   1              62018   1.847814e-04 <U+22EF> 2872
3980   1              62018  -3.576937e-04 <U+22EF>  686
3981   1              62018  -3.966690e-04 <U+22EF>  549
3982   1              62018  -1.811640e-04 <U+22EF> 2549
3983   1              62018  -7.501340e-04 <U+22EF>  125
3984   1              62018   2.075643e-04 <U+22EF> 1467
3985   1              62018  -1.641135e-04 <U+22EF> 1952
3986   1              62018  -3.074323e-04 <U+22EF>  418
3987   1              62018   1.284405e-04 <U+22EF> 1946
3988   1              62018  -1.171199e-04 <U+22EF> 1900
3989   1              62018   1.012548e-04 <U+22EF> 1942
3990   1              62018  -1.171463e-04 <U+22EF>  484
3991   1              62018   7.134526e-05 <U+22EF> 1236
3992   1              62018  -4.250898e-05 <U+22EF> 2292
3993   1              62018   3.445112e-05 <U+22EF>  433
3994   1              62018  -1.585289e-05 <U+22EF> 1700
       homN_Allele2_ctrls hetN_Allele2_ctrls Tstat_cond p.value_cond varT_cond
1      45754              10070              NA         NA           NA
2      45914               9918              NA         NA           NA
3      46947               8995              NA         NA           NA
4      46900               9002              NA         NA           NA
5      46389               9483              NA         NA           NA
6      46385               9483              NA         NA           NA
7      47403               8511              NA         NA           NA
8      46352               9500              NA         NA           NA
9      47136               8653              NA         NA           NA
10     46596               9290              NA         NA           NA
11     37648              16804              NA         NA           NA
12     46929               8951              NA         NA           NA
13     22559              27165              NA         NA           NA
14     40945              14184              NA         NA           NA
15     40890              14228              NA         NA           NA
16     40888              14234              NA         NA           NA
17     41173              13998              NA         NA           NA
18     41169              14009              NA         NA           NA
19     41881              13247              NA         NA           NA
20     46974               8922              NA         NA           NA
21     40944              14194              NA         NA           NA
22     40909              14219              NA         NA           NA
23     23382              25812              NA         NA           NA
24     46686               9177              NA         NA           NA
25     41091              14021              NA         NA           NA
26     41138              13963              NA         NA           NA
27     23330              25879              NA         NA           NA
28     23159              26043              NA         NA           NA
29     47925               8053              NA         NA           NA
30     46946               8943              NA         NA           NA
<U+22EE> <U+22EE>           <U+22EE>           <U+22EE>   <U+22EE>     <U+22EE>
3965    2151              17440              NA         NA           NA
3966    9254              29660              NA         NA           NA
3967   53545               2717              NA         NA           NA
3968   54850               1441              NA         NA           NA
3969   23222              25831              NA         NA           NA
3970    1301              14300              NA         NA           NA
3971   36106              17983              NA         NA           NA
3972   44272              11336              NA         NA           NA
3973   48282               7676              NA         NA           NA
3974   45931               9851              NA         NA           NA
3975   44062              11523              NA         NA           NA
3976    2852              19788              NA         NA           NA
3977    1362              14475              NA         NA           NA
3978   26651              24294              NA         NA           NA
3979   12047              28546              NA         NA           NA
3980   49437               6615              NA         NA           NA
3981   50762               5429              NA         NA           NA
3982   24226              25398              NA         NA           NA
3983   55081               1226              NA         NA           NA
3984   40616              14420              NA         NA           NA
3985   34205              19355              NA         NA           NA
3986   52050               4165              NA         NA           NA
3987   34257              19311              NA         NA           NA
3988    2475              18595              NA         NA           NA
3989   34331              19238              NA         NA           NA
3990   51427               4765              NA         NA           NA
3991   43237              12209              NA         NA           NA
3992    4337              22456              NA         NA           NA
3993   51966               4256              NA         NA           NA
3994   37280              17004              NA         NA           NA
       BETA_cond SE_cond Tstat_new   p.value_new
1      NA        NA      -131.00761  1.316488e-05
2      NA        NA      -127.04118  2.110246e-05
3      NA        NA      -116.22429  4.266169e-05
4      NA        NA      -116.07125  5.033654e-05
5      NA        NA      -117.75372  5.611839e-05
6      NA        NA      -117.83811  5.638033e-05
7      NA        NA      -111.61733  6.447946e-05
8      NA        NA      -116.08727  7.624707e-05
9      NA        NA      -113.51999  8.300154e-05
10     NA        NA      -113.52849  8.902707e-05
11     NA        NA      -135.31939  5.183216e-04
12     NA        NA       -95.20238  8.737224e-04
13     NA        NA      -153.37800  1.038065e-03
14     NA        NA      -116.12639  1.145071e-03
15     NA        NA      -116.10177  1.169640e-03
16     NA        NA      -114.99898  1.301659e-03
17     NA        NA      -113.68643  1.310077e-03
18     NA        NA      -112.86302  1.424739e-03
19     NA        NA      -111.44041  1.465912e-03
20     NA        NA       -90.66620  1.466164e-03
21     NA        NA      -113.44226  1.476164e-03
22     NA        NA      -112.96211  1.569126e-03
23     NA        NA      -151.88726  1.614077e-03
24     NA        NA       -90.71878  1.690307e-03
25     NA        NA      -111.79754  1.708653e-03
26     NA        NA      -111.36953  1.762053e-03
27     NA        NA      -150.16366  1.804553e-03
28     NA        NA      -149.80594  1.810696e-03
29     NA        NA       -83.90820  1.897920e-03
30     NA        NA       -88.59913  1.912949e-03
<U+22EE> <U+22EE>  <U+22EE> <U+22EE>    <U+22EE>
3965   NA        NA      -0.53081124 0.9893746
3966   NA        NA      -0.62853891 0.9894981
3967   NA        NA       0.20567908 0.9896039
3968   NA        NA      -0.14309889 0.9900359
3969   NA        NA       0.60247925 0.9900608
3970   NA        NA       0.44347808 0.9901812
3971   NA        NA       0.46222314 0.9908382
3972   NA        NA      -0.36150387 0.9909359
3973   NA        NA      -0.29525143 0.9910947
3974   NA        NA       0.32438052 0.9913070
3975   NA        NA      -0.34307841 0.9914663
3976   NA        NA      -0.43790003 0.9916855
3977   NA        NA       0.34612475 0.9923975
3978   NA        NA      -0.43887003 0.9924265
3979   NA        NA       0.45810557 0.9926592
3980   NA        NA      -0.21572652 0.9929912
3981   NA        NA      -0.19020263 0.9930696
3982   NA        NA      -0.41494983 0.9930822
3983   NA        NA      -0.08156004 0.9937591
3984   NA        NA       0.26759757 0.9940536
3985   NA        NA      -0.28635799 0.9945303
3986   NA        NA      -0.11565025 0.9952424
3987   NA        NA       0.22328087 0.9957272
3988   NA        NA      -0.19669827 0.9961704
3989   NA        NA       0.17623892 0.9966295
3990   NA        NA      -0.05055866 0.9980582
3991   NA        NA       0.07816184 0.9981158
3992   NA        NA      -0.08662104 0.9984689
3993   NA        NA       0.01330733 0.9994598
3994   NA        NA      -0.02460058 0.9995017

In [122]:
(1:35)[colnames(d) %in% 'p.value_new']

[1] 32

In [89]:
cbind(d, ndf)

       CHR    POS      SNPID       Allele1 Allele2 AC_Allele2 AF_Allele2
1      chr6   30828405 rs117341822 T       A       122506.44  0.9876684
2      chr6   30828768 rs1264350   C       T       103528.34  0.8346636
3      chr6   30828957 rs12198723  G       T       109529.44  0.8830456
4      chr6   30828995 rs114447061 A       T       122468.84  0.9873652
5      chr6   30829155 rs12198842  C       T       108247.16  0.8727076
6      chr6   30829204 rs115919478 T       C       122416.82  0.9869459
7      chr6   30829306 rs9368644   T       C       105897.64  0.8537654
8      chr6   30829438 rs9262218   T       C       120596.45  0.9722697
9      chr6   30829791 rs9262219   C       A       120737.91  0.9734102
10     chr6   30830214 rs7749924   T       C       109310.94  0.8812840
11     chr6   30830391 rs73727477  G       A       122523.85  0.9878088
12     chr6   30830475 rs115015073 T       C       121154.63  0.9767699
13     chr6   30830500 rs78868683  C       G       119273.78  0.9616061
14     chr6   30830699 rs112100248 T       C       122018.02  0.9837307
15     chr6   30832549 rs3130648   T       C        25375.78  0.2045840
16     chr6   30832800 rs1264344   T       C        70243.75  0.5663174
17     chr6   30834286 rs75796258  T       C       121985.39  0.9834676
18     chr6   30834688 rs1264341   C       T       105067.66  0.8470739
19     chr6   30835477 rs3130649   T       A        51270.83  0.4133545
20     chr6   30837669 rs62400982  A       G       117468.36  0.9470506
21     chr6   30838144 rs3095352   T       C        51411.14  0.4144856
22     chr6   30839031 rs73727480  A       G       121954.58  0.9832192
23     chr6   30839116 rs116009799 T       C       122640.59  0.9887499
24     chr6   30839281 rs11757306  C       T       122140.59  0.9847189
25     chr6   30839674 rs111739591 C       T       119707.86  0.9651058
26     chr6   30839880 rs114331468 T       C       122205.12  0.9852391
27     chr6   30839958 rs9262222   G       T       122453.55  0.9872420
28     chr6   30841887 rs2517581   T       C       121460.05  0.9792322
29     chr6   30842087 rs3130787   G       A        47886.97  0.3860732
30     chr6   30842175 rs11752162  G       A       115532.66  0.9314446
<U+22EE> <U+22EE> <U+22EE> <U+22EE>    <U+22EE> <U+22EE> <U+22EE>   <U+22EE>
3965   chr6   32819793 rs2857106   C       T       102206.89  0.8240099
3966   chr6   32820734 rs9784758   C       T       117248.52  0.9452781
3967   chr6   32820935 rs2621322   G       T       101923.62  0.8217261
3968   chr6   32821101 rs9784876   A       C       117239.27  0.9452036
3969   chr6   32821703 rs2621321   G       A        93952.84  0.7574642
3970   chr6   32822282 rs2857105   C       T       118482.26  0.9552248
3971   chr6   32822312 rs16870908  A       G       117722.58  0.9491001
3972   chr6   32823522 rs2857103   A       C        87933.42  0.7089347
3973   chr6   32824916 rs16870923  C       T       121503.88  0.9795856
3974   chr6   32825196 rs1894411   C       T       109275.78  0.8810005
3975   chr6   32825746 rs13501     A       G        87674.74  0.7068492
3976   chr6   32826204 rs1044043   C       A        28787.63  0.2320909
3977   chr6   32827255 rs10484565  A       G       114721.73  0.9249068
3978   chr6   32828188 rs241456    A       G        93323.05  0.7523868
3979   chr6   32828242 rs241455    A       C        93751.33  0.7558397
3980   chr6   32828367 rs241454    G       A        93762.01  0.7559258
3981   chr6   32828449 rs241453    A       G        93765.93  0.7559574
3982   chr6   32828533 rs115360810 G       A       120337.41  0.9701813
3983   chr6   32828744 rs17034     T       C        93998.11  0.7578293
3984   chr6   32828876 rs241449    A       C        93718.94  0.7555785
3985   chr6   32828908 rs241448    G       A        93506.98  0.7538697
3986   chr6   32828974 rs241447    C       T        93647.82  0.7550052
3987   chr6   32829016 rs4148876   A       G       115320.60  0.9297349
3988   chr6   32829584 rs241440    T       C        93869.95  0.7567960
3989   chr6   32829711 rs4148874   T       C        32915.83  0.2653732
3990   chr6   32829760 rs241439    G       T        75191.96  0.6062108
3991   chr6   32829843 rs241438    T       C        79584.51  0.6416243
3992   chr6   32829907 rs241437    G       A        74860.38  0.6035376
3993   chr6   32830032 rs2228396   T       C       111603.58  0.8997676
3994   chr6   32830099 rs241436    G       A        68335.67  0.5509341
       imputationInfo N      BETA          <U+22EF>   N.Controls
1      1              62018   0.058462765  <U+22EF> 56307
2      1              62018   0.018588563  <U+22EF> 56307
3      1              62018   0.020311651  <U+22EF> 56307
4      1              62018   0.082108619  <U+22EF> 56307
5      1              62018   0.015210392  <U+22EF> 56307
6      1              62018   0.010982588  <U+22EF> 56307
7      1              62018  -0.028971353  <U+22EF> 56307
8      1              62018  -0.084990319  <U+22EF> 56307
9      1              62018  -0.079485051  <U+22EF> 56307
10     1              62018  -0.011945323  <U+22EF> 56307
11     1              62018  -0.229420745  <U+22EF> 56307
12     1              62018  -0.060835381  <U+22EF> 56307
13     1              62018  -0.120116627  <U+22EF> 56307
14     1              62018  -0.069363755  <U+22EF> 56307
15     1              62018  -0.025694278  <U+22EF> 56307
16     1              62018  -0.014691913  <U+22EF> 56307
17     1              62018  -0.008141326  <U+22EF> 56307
18     1              62018   0.026620973  <U+22EF> 56307
19     1              62018   0.004018738  <U+22EF> 56307
20     1              62018   0.050324904  <U+22EF> 56307
21     1              62018   0.003877342  <U+22EF> 56307
22     1              62018   0.022015287  <U+22EF> 56307
23     1              62018  -0.088765523  <U+22EF> 56307
24     1              62018  -0.044201980  <U+22EF> 56307
25     1              62018   0.060022694  <U+22EF> 56307
26     1              62018   0.149188055  <U+22EF> 56307
27     1              62018  -0.219958042  <U+22EF> 56307
28     1              62018   0.040760666  <U+22EF> 56307
29     1              62018  -0.009974395  <U+22EF> 56307
30     1              62018  -0.010785547  <U+22EF> 56307
<U+22EE> <U+22EE>       <U+22EE> <U+22EE>      <U+22F1> <U+22EE>
3965   1              62018   0.0003660739 <U+22EF> 56307
3966   1              62018  -0.0282544158 <U+22EF> 56307
3967   1              62018   0.0058899695 <U+22EF> 56307
3968   1              62018  -0.0320499730 <U+22EF> 56307
3969   1              62018   0.0227939290 <U+22EF> 56307
3970   1              62018  -0.0907498048 <U+22EF> 56307
3971   1              62018  -0.0165472886 <U+22EF> 56307
3972   1              62018   0.0177352906 <U+22EF> 56307
3973   1              62018  -0.0522816400 <U+22EF> 56307
3974   1              62018  -0.0804409964 <U+22EF> 56307
3975   1              62018   0.0167721020 <U+22EF> 56307
3976   1              62018   0.0041826199 <U+22EF> 56307
3977   1              62018   0.0281878303 <U+22EF> 56307
3978   1              62018   0.0148827488 <U+22EF> 56307
3979   1              62018   0.0218871325 <U+22EF> 56307
3980   1              62018   0.0192631636 <U+22EF> 56307
3981   1              62018   0.0257616338 <U+22EF> 56307
3982   1              62018   0.0194372240 <U+22EF> 56307
3983   1              62018   0.0200292476 <U+22EF> 56307
3984   1              62018   0.0210727700 <U+22EF> 56307
3985   1              62018   0.0167733373 <U+22EF> 56307
3986   1              62018   0.0218959908 <U+22EF> 56307
3987   1              62018  -0.0224614239 <U+22EF> 56307
3988   1              62018   0.0168990925 <U+22EF> 56307
3989   1              62018  -0.0082801675 <U+22EF> 56307
3990   1              62018   0.0329050839 <U+22EF> 56307
3991   1              62018   0.0405213551 <U+22EF> 56307
3992   1              62018   0.0365601560 <U+22EF> 56307
3993   1              62018  -0.0038959144 <U+22EF> 56307
3994   1              62018   0.0193713231 <U+22EF> 56307
       homN_Allele2_cases hetN_Allele2_cases homN_Allele2_ctrls
1      5576                135               54915
2      3999               1575               39276
3      4471               1166               43928
4      5577                134               54908
5      4358               1268               42869
6      5567                142               54866
7      4129               1462               41092
8      5373                333               53254
9      5392                315               53399
10     4426               1201               43742
11     5545                163               54971
12     5434                273               53741
13     5242                460               52107
14     5518                190               54501
15      219               1854                2406
16     1842               2740               17954
17     5519                192               54455
18     4133               1453               40377
19     1014               2711                9546
20     5157                530               50511
21     1030               2692                9717
22     5521                190               54425
23     5574                134               55058
24     5534                174               54611
25     5337                369               52429
26     5562                149               54629
27     5538                171               54912
28     5487                222               53977
29      878               2638                8340
30     4947                738               48863
<U+22EE> <U+22EE>           <U+22EE>           <U+22EE>
3965   3873               1676               38177
3966   5083                616               50321
3967   3859               1683               37974
3968   5081                617               50311
3969   3331               2039               32276
3970   5175                525               51446
3971   5135                563               50730
3972   2926               2275               28166
3973   5469                241               54039
3974   4354               1269               43784
3975   2908               2290               28042
3976    328               1995                3376
3977   4897                788               48180
3978   3328               1979               32240
3979   3319               2045               32162
3980   3314               2046               32151
3981   3326               2040               32164
3982   5390                318               53086
3983   3330               2040               32317
3984   3316               2047               32128
3985   3306               2053               32106
3986   3318               2043               32149
3987   4930                756               48736
3988   3322               2038               32233
3989    394               2230                3934
3990   2168               2671               20660
3991   2425               2569               23118
3992   2142               2697               20407
3993   4622               1031               45593
3994   1776               2791               16997
       hetN_Allele2_ctrls Tstat_cond p.value_cond varT_cond BETA_cond SE_cond
1       1392              NA         NA           NA        NA        NA
2      15445              NA         NA           NA        NA        NA
3      11590              NA         NA           NA        NA        NA
4       1380              NA         NA           NA        NA        NA
5      12544              NA         NA           NA        NA        NA
6       1429              NA         NA           NA        NA        NA
7      14003              NA         NA           NA        NA        NA
8       3011              NA         NA           NA        NA        NA
9       2890              NA         NA           NA        NA        NA
10     11787              NA         NA           NA        NA        NA
11      1330              NA         NA           NA        NA        NA
12      2534              NA         NA           NA        NA        NA
13      4121              NA         NA           NA        NA        NA
14      1791              NA         NA           NA        NA        NA
15     18228              NA         NA           NA        NA        NA
16     27864              NA         NA           NA        NA        NA
17      1852              NA         NA           NA        NA        NA
18     14602              NA         NA           NA        NA        NA
19     27466              NA         NA           NA        NA        NA
20      5612              NA         NA           NA        NA        NA
21     27259              NA         NA           NA        NA        NA
22      1876              NA         NA           NA        NA        NA
23      1244              NA         NA           NA        NA        NA
24      1678              NA         NA           NA        NA        NA
25      3816              NA         NA           NA        NA        NA
26      1675              NA         NA           NA        NA        NA
27      1384              NA         NA           NA        NA        NA
28      2311              NA         NA           NA        NA        NA
29     26841              NA         NA           NA        NA        NA
30      7187              NA         NA           NA        NA        NA
<U+22EE> <U+22EE>           <U+22EE>   <U+22EE>     <U+22EE>  <U+22EE>  <U+22EE>
3965   16521              NA         NA           NA        NA        NA
3966    5829              NA         NA           NA        NA        NA
3967   16601              NA         NA           NA        NA        NA
3968    5842              NA         NA           NA        NA        NA
3969   20727              NA         NA           NA        NA        NA
3970    4780              NA         NA           NA        NA        NA
3971    5448              NA         NA           NA        NA        NA
3972   23329              NA         NA           NA        NA        NA
3973    2251              NA         NA           NA        NA        NA
3974   11771              NA         NA           NA        NA        NA
3975   23426              NA         NA           NA        NA        NA
3976   19328              NA         NA           NA        NA        NA
3977    7791              NA         NA           NA        NA        NA
3978   20317              NA         NA           NA        NA        NA
3979   20800              NA         NA           NA        NA        NA
3980   20807              NA         NA           NA        NA        NA
3981   20784              NA         NA           NA        NA        NA
3982    3171              NA         NA           NA        NA        NA
3983   20714              NA         NA           NA        NA        NA
3984   20825              NA         NA           NA        NA        NA
3985   20851              NA         NA           NA        NA        NA
3986   20809              NA         NA           NA        NA        NA
3987    7312              NA         NA           NA        NA        NA
3988   20738              NA         NA           NA        NA        NA
3989   22073              NA         NA           NA        NA        NA
3990   26852              NA         NA           NA        NA        NA
3991   25889              NA         NA           NA        NA        NA
3992   27019              NA         NA           NA        NA        NA
3993   10152              NA         NA           NA        NA        NA
3994   27984              NA         NA           NA        NA        NA

In [63]:
colnames(new_col) <- cond_cols[1]

In [64]:
cbind(d, new_col)

       CHR    POS      SNPID       Allele1 Allele2 AC_Allele2 AF_Allele2
1      chr6   30828405 rs117341822 T       A       122506.44  0.9876684
2      chr6   30828768 rs1264350   C       T       103528.34  0.8346636
3      chr6   30828957 rs12198723  G       T       109529.44  0.8830456
4      chr6   30828995 rs114447061 A       T       122468.84  0.9873652
5      chr6   30829155 rs12198842  C       T       108247.16  0.8727076
6      chr6   30829204 rs115919478 T       C       122416.82  0.9869459
7      chr6   30829306 rs9368644   T       C       105897.64  0.8537654
8      chr6   30829438 rs9262218   T       C       120596.45  0.9722697
9      chr6   30829791 rs9262219   C       A       120737.91  0.9734102
10     chr6   30830214 rs7749924   T       C       109310.94  0.8812840
11     chr6   30830391 rs73727477  G       A       122523.85  0.9878088
12     chr6   30830475 rs115015073 T       C       121154.63  0.9767699
13     chr6   30830500 rs78868683  C       G       119273.78  0.9616061
14     chr6   30830699 rs112100248 T       C       122018.02  0.9837307
15     chr6   30832549 rs3130648   T       C        25375.78  0.2045840
16     chr6   30832800 rs1264344   T       C        70243.75  0.5663174
17     chr6   30834286 rs75796258  T       C       121985.39  0.9834676
18     chr6   30834688 rs1264341   C       T       105067.66  0.8470739
19     chr6   30835477 rs3130649   T       A        51270.83  0.4133545
20     chr6   30837669 rs62400982  A       G       117468.36  0.9470506
21     chr6   30838144 rs3095352   T       C        51411.14  0.4144856
22     chr6   30839031 rs73727480  A       G       121954.58  0.9832192
23     chr6   30839116 rs116009799 T       C       122640.59  0.9887499
24     chr6   30839281 rs11757306  C       T       122140.59  0.9847189
25     chr6   30839674 rs111739591 C       T       119707.86  0.9651058
26     chr6   30839880 rs114331468 T       C       122205.12  0.9852391
27     chr6   30839958 rs9262222   G       T       122453.55  0.9872420
28     chr6   30841887 rs2517581   T       C       121460.05  0.9792322
29     chr6   30842087 rs3130787   G       A        47886.97  0.3860732
30     chr6   30842175 rs11752162  G       A       115532.66  0.9314446
<U+22EE> <U+22EE> <U+22EE> <U+22EE>    <U+22EE> <U+22EE> <U+22EE>   <U+22EE>
3965   chr6   32819793 rs2857106   C       T       102206.89  0.8240099
3966   chr6   32820734 rs9784758   C       T       117248.52  0.9452781
3967   chr6   32820935 rs2621322   G       T       101923.62  0.8217261
3968   chr6   32821101 rs9784876   A       C       117239.27  0.9452036
3969   chr6   32821703 rs2621321   G       A        93952.84  0.7574642
3970   chr6   32822282 rs2857105   C       T       118482.26  0.9552248
3971   chr6   32822312 rs16870908  A       G       117722.58  0.9491001
3972   chr6   32823522 rs2857103   A       C        87933.42  0.7089347
3973   chr6   32824916 rs16870923  C       T       121503.88  0.9795856
3974   chr6   32825196 rs1894411   C       T       109275.78  0.8810005
3975   chr6   32825746 rs13501     A       G        87674.74  0.7068492
3976   chr6   32826204 rs1044043   C       A        28787.63  0.2320909
3977   chr6   32827255 rs10484565  A       G       114721.73  0.9249068
3978   chr6   32828188 rs241456    A       G        93323.05  0.7523868
3979   chr6   32828242 rs241455    A       C        93751.33  0.7558397
3980   chr6   32828367 rs241454    G       A        93762.01  0.7559258
3981   chr6   32828449 rs241453    A       G        93765.93  0.7559574
3982   chr6   32828533 rs115360810 G       A       120337.41  0.9701813
3983   chr6   32828744 rs17034     T       C        93998.11  0.7578293
3984   chr6   32828876 rs241449    A       C        93718.94  0.7555785
3985   chr6   32828908 rs241448    G       A        93506.98  0.7538697
3986   chr6   32828974 rs241447    C       T        93647.82  0.7550052
3987   chr6   32829016 rs4148876   A       G       115320.60  0.9297349
3988   chr6   32829584 rs241440    T       C        93869.95  0.7567960
3989   chr6   32829711 rs4148874   T       C        32915.83  0.2653732
3990   chr6   32829760 rs241439    G       T        75191.96  0.6062108
3991   chr6   32829843 rs241438    T       C        79584.51  0.6416243
3992   chr6   32829907 rs241437    G       A        74860.38  0.6035376
3993   chr6   32830032 rs2228396   T       C       111603.58  0.8997676
3994   chr6   32830099 rs241436    G       A        68335.67  0.5509341
       imputationInfo N      BETA          <U+22EF>   varTstar  AF.Cases
1      1              62018   0.058462765  <U+22EF>  124.0889 0.9881613
2      1              62018   0.018588563  <U+22EF> 1407.1975 0.8378299
3      1              62018   0.020311651  <U+22EF> 1056.6187 0.8847950
4      1              62018   0.082108619  <U+22EF>  129.3135 0.9881444
5      1              62018   0.015210392  <U+22EF> 1130.6970 0.8739912
6      1              62018   0.010982588  <U+22EF>  130.8802 0.9870622
7      1              62018  -0.028971353  <U+22EF> 1278.4406 0.8508869
8      1              62018  -0.084990319  <U+22EF>  277.0062 0.9699654
9      1              62018  -0.079485051  <U+22EF>  259.4692 0.9713162
10     1              62018  -0.011945323  <U+22EF> 1069.4291 0.8800604
11     1              62018  -0.229420745  <U+22EF>  124.5562 0.9851933
12     1              62018  -0.060835381  <U+22EF>  233.6362 0.9753862
13     1              62018  -0.120116627  <U+22EF>  372.0069 0.9580972
14     1              62018  -0.069363755  <U+22EF>  163.0181 0.9828344
15     1              62018  -0.025694278  <U+22EF> 1666.8562 0.2010594
16     1              62018  -0.014691913  <U+22EF> 2492.7859 0.5627834
17     1              62018  -0.008141326  <U+22EF>  164.8113 0.9831614
18     1              62018   0.026620973  <U+22EF> 1316.4524 0.8508750
19     1              62018   0.004018738  <U+22EF> 2471.2868 0.4146887
20     1              62018   0.050324904  <U+22EF>  517.6561 0.9493217
21     1              62018   0.003877342  <U+22EF> 2493.7869 0.4157397
22     1              62018   0.022015287  <U+22EF>  168.5333 0.9833449
23     1              62018  -0.088765523  <U+22EF>  115.0135 0.9877370
24     1              62018  -0.044201980  <U+22EF>  153.7495 0.9842383
25     1              62018   0.060022694  <U+22EF>  343.3617 0.9667268
26     1              62018   0.149188055  <U+22EF>  148.8287 0.9869524
27     1              62018  -0.219958042  <U+22EF>  130.2693 0.9846675
28     1              62018   0.040760666  <U+22EF>  204.3505 0.9802063
29     1              62018  -0.009974395  <U+22EF> 2418.7319 0.3845167
30     1              62018  -0.010785547  <U+22EF>  649.7795 0.9307512
<U+22EE> <U+22EE>       <U+22EE> <U+22EE>      <U+22F1> <U+22EE>  <U+22EE>
3965   1              62018   0.0003660739 <U+22EF> 1452.1331 0.8242214
3966   1              62018  -0.0282544158 <U+22EF>  526.8870 0.9439295
3967   1              62018   0.0058899695 <U+22EF> 1482.3251 0.8227798
3968   1              62018  -0.0320499730 <U+22EF>  527.2688 0.9436859
3969   1              62018   0.0227939290 <U+22EF> 1876.8851 0.7615207
3970   1              62018  -0.0907498048 <U+22EF>  428.2204 0.9517101
3971   1              62018  -0.0165472886 <U+22EF>  490.8045 0.9483348
3972   1              62018   0.0177352906 <U+22EF> 2112.0093 0.7124362
3973   1              62018  -0.0522816400 <U+22EF>  202.7676 0.9786967
3974   1              62018  -0.0804409964 <U+22EF> 1067.5342 0.8730313
3975   1              62018   0.0167721020 <U+22EF> 2117.0428 0.7101901
3976   1              62018   0.0041826199 <U+22EF> 1876.8596 0.2326649
3977   1              62018   0.0281878303 <U+22EF>  710.6787 0.9263920
3978   1              62018   0.0148827488 <U+22EF> 1958.4075 0.7552168
3979   1              62018   0.0218871325 <U+22EF> 1883.7344 0.7597293
3980   1              62018   0.0192631636 <U+22EF> 1886.8011 0.7593689
3981   1              62018   0.0257616338 <U+22EF> 1886.0654 0.7605602
3982   1              62018   0.0194372240 <U+22EF>  287.0860 0.9707722
3983   1              62018   0.0200292476 <U+22EF> 1871.3939 0.7613487
3984   1              62018   0.0210727700 <U+22EF> 1886.4568 0.7592930
3985   1              62018   0.0167733373 <U+22EF> 1879.5432 0.7568567
3986   1              62018   0.0218959908 <U+22EF> 1881.7401 0.7589485
3987   1              62018  -0.0224614239 <U+22EF>  657.5801 0.9286716
3988   1              62018   0.0168990925 <U+22EF> 1884.5128 0.7598566
3989   1              62018  -0.0082801675 <U+22EF> 1984.8516 0.2638161
3990   1              62018   0.0329050839 <U+22EF> 2447.7259 0.6135582
3991   1              62018   0.0405213551 <U+22EF> 2357.3084 0.6500568
3992   1              62018   0.0365601560 <U+22EF> 2444.8566 0.6116240
3993   1              62018  -0.0038959144 <U+22EF>  921.8972 0.8995447
3994   1              62018   0.0193713231 <U+22EF> 2522.1358 0.5555013
       AF.Controls N.Cases N.Controls homN_Allele2_cases hetN_Allele2_cases
1      0.9876184   5711    56307      5576                135
2      0.8343425   5711    56307      3999               1575
3      0.8828681   5711    56307      4471               1166
4      0.9872862   5711    56307      5577                134
5      0.8725774   5711    56307      4358               1268
6      0.9869341   5711    56307      5567                142
7      0.8540573   5711    56307      4129               1462
8      0.9725034   5711    56307      5373                333
9      0.9736227   5711    56307      5392                315
10     0.8814081   5711    56307      4426               1201
11     0.9880741   5711    56307      5545                163
12     0.9769102   5711    56307      5434                273
13     0.9619620   5711    56307      5242                460
14     0.9838216   5711    56307      5518                190
15     0.2049415   5711    56307       219               1854
16     0.5666759   5711    56307      1842               2740
17     0.9834987   5711    56307      5519                192
18     0.8466884   5711    56307      4133               1453
19     0.4132191   5711    56307      1014               2711
20     0.9468202   5711    56307      5157                530
21     0.4143584   5711    56307      1030               2692
22     0.9832065   5711    56307      5521                190
23     0.9888526   5711    56307      5574                134
24     0.9847677   5711    56307      5534                174
25     0.9649413   5711    56307      5337                369
26     0.9850653   5711    56307      5562                149
27     0.9875031   5711    56307      5538                171
28     0.9791334   5711    56307      5487                222
29     0.3862311   5711    56307       878               2638
30     0.9315149   5711    56307      4947                738
<U+22EE> <U+22EE>    <U+22EE> <U+22EE>   <U+22EE>           <U+22EE>
3965   0.8239885   5711    56307      3873               1676
3966   0.9454149   5711    56307      5083                616
3967   0.8216192   5711    56307      3859               1683
3968   0.9453575   5711    56307      5081                617
3969   0.7570528   5711    56307      3331               2039
3970   0.9555812   5711    56307      5175                525
3971   0.9491777   5711    56307      5135                563
3972   0.7085795   5711    56307      2926               2275
3973   0.9796757   5711    56307      5469                241
3974   0.8818088   5711    56307      4354               1269
3975   0.7065103   5711    56307      2908               2290
3976   0.2320327   5711    56307       328               1995
3977   0.9247561   5711    56307      4897                788
3978   0.7520998   5711    56307      3328               1979
3979   0.7554452   5711    56307      3319               2045
3980   0.7555766   5711    56307      3314               2046
3981   0.7554905   5711    56307      3326               2040
3982   0.9701214   5711    56307      5390                318
3983   0.7574723   5711    56307      3330               2040
3984   0.7552018   5711    56307      3316               2047
3985   0.7535667   5711    56307      3306               2053
3986   0.7546052   5711    56307      3318               2043
3987   0.9298428   5711    56307      4930                756
3988   0.7564856   5711    56307      3322               2038
3989   0.2655311   5711    56307       394               2230
3990   0.6054655   5711    56307      2168               2671
3991   0.6407690   5711    56307      2425               2569
3992   0.6027174   5711    56307      2142               2697
3993   0.8997902   5711    56307      4622               1031
3994   0.5504709   5711    56307      1776               2791
       homN_Allele2_ctrls hetN_Allele2_ctrls Tstat_cond
1      54915               1392              NA
2      39276              15445              NA
3      43928              11590              NA
4      54908               1380              NA
5      42869              12544              NA
6      54866               1429              NA
7      41092              14003              NA
8      53254               3011              NA
9      53399               2890              NA
10     43742              11787              NA
11     54971               1330              NA
12     53741               2534              NA
13     52107               4121              NA
14     54501               1791              NA
15      2406              18228              NA
16     17954              27864              NA
17     54455               1852              NA
18     40377              14602              NA
19      9546              27466              NA
20     50511               5612              NA
21      9717              27259              NA
22     54425               1876              NA
23     55058               1244              NA
24     54611               1678              NA
25     52429               3816              NA
26     54629               1675              NA
27     54912               1384              NA
28     53977               2311              NA
29      8340              26841              NA
30     48863               7187              NA
<U+22EE> <U+22EE>           <U+22EE>           <U+22EE>
3965   38177              16521              NA
3966   50321               5829              NA
3967   37974              16601              NA
3968   50311               5842              NA
3969   32276              20727              NA
3970   51446               4780              NA
3971   50730               5448              NA
3972   28166              23329              NA
3973   54039               2251              NA
3974   43784              11771              NA
3975   28042              23426              NA
3976    3376              19328              NA
3977   48180               7791              NA
3978   32240              20317              NA
3979   32162              20800              NA
3980   32151              20807              NA
3981   32164              20784              NA
3982   53086               3171              NA
3983   32317              20714              NA
3984   32128              20825              NA
3985   32106              20851              NA
3986   32149              20809              NA
3987   48736               7312              NA
3988   32233              20738              NA
3989    3934              22073              NA
3990   20660              26852              NA
3991   23118              25889              NA
3992   20407              27019              NA
3993   45593              10152              NA
3994   16997              27984              NA

In [38]:
x = lapply(files_chr, read.table, header = TRUE)

In [40]:
files

 [1] "../data/conditional/common/211111_spa_conditional_synonymous_breast_cancer_conditioning_markers.txt"
 [2] "../data/conditional/common/211111_spa_conditional_synonymous_breast_cancer_i1.txt"
 [3] "../data/conditional/common/211111_spa_conditional_synonymous_breast_cancer_i10.txt"
 [4] "../data/conditional/common/211111_spa_conditional_synonymous_breast_cancer_i1_chr5"
 [5] "../data/conditional/common/211111_spa_conditional_synonymous_breast_cancer_i1_chr6"
 [6] "../data/conditional/common/211111_spa_conditional_synonymous_breast_cancer_i2.txt"
 [7] "../data/conditional/common/211111_spa_conditional_synonymous_breast_cancer_i2_chr5"
 [8] "../data/conditional/common/211111_spa_conditional_synonymous_breast_cancer_i2_chr6"
 [9] "../data/conditional/common/211111_spa_conditional_synonymous_breast_cancer_i3.txt"
[10] "../data/conditional/common/211111_spa_conditional_synonymous_breast_cancer_i4.txt"
[11] "../data/conditional/common/211111_spa_conditional_synonymous_breast_cancer_i5.txt"
[12] "../data/conditional/common/211111_spa_conditional_synonymous_breast_cancer_i6.txt"
[13] "../data/conditional/common/211111_spa_conditional_synonymous_breast_cancer_i7.txt"
[14] "../data/conditional/common/211111_spa_conditional_synonymous_breast_cancer_i8.txt"
[15] "../data/conditional/common/211111_spa_conditional_synonymous_breast_cancer_i9.txt"

In [44]:
x1 = read.table("../data/conditional/common/211111_spa_conditional_synonymous_breast_cancer_i1_chr6", header = TRUE)
x2 = read.table("../data/conditional/common/211111_spa_conditional_synonymous_breast_cancer_i2_chr6", header = TRUE)

In [47]:
colnames(x1)

 [1] "CHR"                "POS"                "SNPID"
 [4] "Allele1"            "Allele2"            "AC_Allele2"
 [7] "AF_Allele2"         "imputationInfo"     "N"
[10] "BETA"               "SE"                 "Tstat"
[13] "p.value"            "p.value.NA"         "Is.SPA.converge"
[16] "varT"               "varTstar"           "AF.Cases"
[19] "AF.Controls"        "N.Cases"            "N.Controls"
[22] "homN_Allele2_cases" "hetN_Allele2_cases" "homN_Allele2_ctrls"
[25] "hetN_Allele2_ctrls"

In [48]:
colnames(x2)

 [1] "CHR"                "POS"                "SNPID"
 [4] "Allele1"            "Allele2"            "AC_Allele2"
 [7] "AF_Allele2"         "imputationInfo"     "N"
[10] "BETA"               "SE"                 "Tstat"
[13] "p.value"            "p.value.NA"         "Is.SPA.converge"
[16] "varT"               "varTstar"           "Tstat_cond"
[19] "p.value_cond"       "varT_cond"          "BETA_cond"
[22] "SE_cond"            "AF.Cases"           "AF.Controls"
[25] "N.Cases"            "N.Controls"         "homN_Allele2_cases"
[28] "hetN_Allele2_cases" "homN_Allele2_ctrls" "hetN_Allele2_ctrls"

In [49]:
colnames(x2)[!colnames(x2) %in% colnames(x1)]

[1] "Tstat_cond"   "p.value_cond" "varT_cond"    "BETA_cond"    "SE_cond"